FluentFTP/FtpClient.cs

Infinite recursion calls happens, when FtpListItem is referencing to parent or current directory and when `MLSD` command is used for `GetListing` method.

Fixes DeleteDirectory infinite recursion calls

---

FluentFTP.Tests/Program.cs
FluentFTP/FluentFTP.csproj
FluentFTP/FtpClient.cs
FluentFTP/FtpClientHttp11Proxy.cs
FluentFTP/FtpClientProxy.cs
FluentFTP/FtpClientUserAtHostProxy.cs
FluentFTP/Proxy.cs

For #7 
HTTP1.1 proxy with or without authentication,
User@Host, with or without authentication.
Futur proxy implementation will benefit from FtpClientProxy abstract class.
Usage : 
using (FtpClient cl = new FtpClientHttp11Proxy(new Proxy { Host = "127.0.0.1", Port = 3128, }))
...

New - Support proxy HTTP 1.1/ User@Host

---

FluentFTP/FtpClient.cs

I noticed that on Windows-Vista machine (Running on Mono Runtime) m_stream.LocalEndPoint migtht be null.
With the 2 changes the exceptions were eliminated. I did not see the reason for missing local endpoint data and there are much more references to be fixed. Perhaps it might be wise to create an dummy item to prevent Exceptions.

LocalEndpoint can be null

---

FluentFTP/FtpExceptions.cs

All custom exceptions has to have [Serializable] attribute to make sure they can be serialized when go thru WCF communication for example, or if roaming between AppDomain's.

Added Serializable attribute to defined Exceptions

---

FluentFTP/FtpClient.cs

If `localPath` is just a filename, say 'file.txt', then the directory part returned by `Path.GetDirectoryName(localPath)` will be the empty string. Passing that to `Directory.Exists(dirPath)` will cause an exception.
This change ensures that we never pass the empty string to `Directory.Exists(dirPath)`. We can safely make this change, because if `dirPath` is the empty string, then we are downloading to the current directory, which definitely exists, so there is no need to create a new directory.
This fixes issue #115.

Check dirPath is not empty string

---

FluentFTP/Client/FtpClient_HighLevel.cs

We found two issues with the high level transfer functions.   This pull request fixes both.
1.  The UploadDataType and DownloadDataType properties are ignored in most cases.   So, if you set the DownloadDataType to ASCII - the file will still download in Binary unless the server aborts the connection.  (then the retry will set the correct datatype).
**Fix:** Honor the Upload/DownloadDataType properties in all cases.
2. Unknown size ASCII files won't transfer.  Some of FTP servers won't allow you to download a 0 byte file in ASCII mode.  There's code in the high level methods to work around this issue - but it also blocks transfer of 'unknown size' files in ASCII mode.   This creates a problem since some systems don't support the 'SIZE' subcommand (AS400, possibly S390), but require that …

High level API - ASCII mode transfer fixes

---

FluentFTP/Client/FtpClient_Listing.cs
FluentFTP/Stream/FtpSocketStream.cs

GetListing is based on FtpSocketStream.ReadLine to read the list of files returned by the ftp server.
ReadLine method is used across the library to read **only** the bytes required till the end of the line, so it is basically a FtpSocketStream.read of 1 char at a time.
Reading GetListing result char by char is a huge performance issue (considering also the AsyncWaitHandle.WaitOne method used for each Read).
I've added a method to FtpSocketStream class, ReadAllLines, which is able to read n characters in a single call (at the moment 100) and return the list of all lines retrieved by the server.
I've tested it with a big FTP folder (4846 files) with following results:
- current implementation: 3.6-3.8 seconds to get the full list
- modified implementation: 0.48-0.55 seconds
so, ~600% faster …

Increase performance of GetListing method

---

FluentFTP/Helpers/FtpTrace.cs

Marks the TraceSource as volatile thus avoiding compiler optimizations

Fix  for #145

---

FluentFTP/Stream/FtpDataStream.cs
FluentFTP/Stream/FtpSocketStream.cs

This resolves issue #167.
The change here was to move all of the clean-up functionality to the `Dispose(bool)` overrides and simply use the `Close()` methods to call `Dispose()`.
As `FtpDataStream.Dispose(bool)` handles the reply from the control connection, we store this in a field so it may be returned from the shadowing `FtpDataStream.Close()` method.

Dispose of FtpDataStream Now Reads Control Reply

---

FluentFTP/Client/FtpClient_HighLevel.cs

An additional fix for issue #167.
This is no longer necessary now that FtpDataStream correctly handles the final reply itself.

Removed the fixes from high-level functions which read the final reply

---

FluentFTP/Client/FtpClient_HighLevel.cs

Per the .NET Stream API, Read returns zero ONLY on end-of-stream.
Thus, the file upload should not continue after the inner read/write
loop terminates without error.
Stream.Length should not be relied upon for this purpose, as many
implementations of Stream may be buffered, and there is no guarantee
that the length of the Stream is the size of the file.
Resolves #174

Fix file upload EOS bug.

---

FluentFTP/Stream/FtpDataStream.cs
FluentFTP/Stream/FtpSocketStream.cs

While working on the project testing, I stumbled upon a problem with some operations when running in .NET Standard. The library worked fine in .NET Framework, although it only did because it worked around the bug in the first place.
The .NET `Stream` class has three methods (relevant to this issue): `Close()`, `Dispose()` and `Dispose(bool)`. Both dispose methods are blank.  
`Dispose()` calls `Close()`  
`Close()` calls `Dispose(bool)`
The .NET Core's `Stream` class only has `Dispose()` and `Dispose(bool)`, both are blank.
To compensate for the missing `Close()`, the `FtpSocketStream` creates a new `Dispose()` method that calls `Close()`, overrides the `Close()` method (**not calling base.Close()**, and so not calling `Dispose(bool)`). For .NET Core, it creates a `Close()` method, and …

Fixing incorrect stream closing/disposing

---

FluentFTP/Client/FtpClient_Connection.cs
FluentFTP/Client/FtpClient_Hash.cs
FluentFTP/Client/FtpClient_HighLevel.cs
FluentFTP/Client/FtpClient_Listing.cs
FluentFTP/Client/FtpClient_LowLevel.cs
FluentFTP/Client/FtpClient_Management.cs
FluentFTP/FluentFTP.csproj
FluentFTP/Stream/FtpDataStream.cs
FluentFTP/Stream/FtpSocketStream.cs

In a number of places in code the library uses `#if NET45 || CORE` to check if the framework supports await/async keywords. To make it more readable, I've added a `ASYNC` compiler keyword.
Also, I noticed that the library defaults to SSL3 + TLS 1.0 by default on .NET core. SSL3 is now considered obsolete and insecure, and the default since .NET 4.6 is to use TLS 1.0-1.2, so I've updated that.
The FtpClient class has an override to customise that (say you want to connect to older servers), but it was ignored by the `FtpSocketStream` class, so I've rectified that as well, making sure that we store the default `SslProtocols` value in a single place.

Async compiler keyword + More secure SSL protocols

---

FluentFTP/Stream/FtpSocketStream.cs

m_netStream was never assigned in FtpSocketStream for netcore in active mode #221

Bugfix active ftp for netcore

---

FluentFTP/Client/FtpClient_LowLevel.cs

CurrentDataType was not modified in SetDataTypeAsync(), so if async methods are used, the downloading may not switch to correct data type. Causing some files to be downloaded in ASCII mode accidentally and sometimes cause unexpected end of stream exception.
In SetDataType(), CurrentDataType is modified, and now SetDataTypeAsync is set to the same behavior.

Fix a DownloadFileAsync/UploadFileAsync bug

---

FluentFTP/Client/FtpClient_HighLevel.cs
FluentFTP/Stream/FtpDataStream.cs
FluentFTP/Stream/FtpSocketStream.cs

1. fix wrong type checking in DownloadFileInternal and DownloadFileInternalAsync
2. fix the bug that sometimes FtpSocketStream and FtpDataStream are not disposed in Dispose()

Bug fixes for file downloading

---

appveyor.yml

AppVeyor recognized the two testing commands as one. Adding a new line between should fix this.

Fix AppVeyor failure

---

FluentFTP/Client/IFtpClient.cs

This enables the interface to be used in a using() block

Make IFtpClient inherit from IDisposable

---

FluentFTP/Client/FtpClient_HighLevel.cs

UWP does not allow File.Exists() to run in UI thread and throws an exception when doing that. [See StackOverflow entry](https://stackoverflow.com/questions/35747635/perform-synchronous-operation-on-ui-thread) 
The File.Exists() in asynchronous methods are wrapped in Task.Run to fix this.
The ones in synchronous methods are not changed because synchronous methods are not supposed to be used in UI thread.

Check file existence in background thread

---

FluentFTP/Client/FtpClient_HighLevel.cs

Throw OperationCanceledException instead of FtpException when cancellation is requested.

Throw OperationCanceledException when cancellation is requested

---

FluentFTP/Client/FtpClient_Connection.cs
FluentFTP/Client/FtpClient_LowLevel.cs

* FtpClient_LowLevel.cs need to break the foreach loop when a port is successful otherwise we get errors.
* FtpClient_Connection.cs needs to clone the ActivePorts as well when using EnableThreadSafeDataConnections.

Fixes for using active FTP and specifying the ActivePorts

---

FluentFTP/Client/FtpClient_Connection.cs
FluentFTP/Client/FtpClient_Hash.cs
FluentFTP/Client/FtpClient_Listing.cs
FluentFTP/Client/FtpClient_LowLevel.cs
FluentFTP/Client/FtpClient_Management.cs

Fix a race condition when BeginInvoke calls the callback before the IAsyncResult is added to m_asyncmethods.
By moving the BeginInvoke inside of the lock it is no longer possible for the End method to be called before the IAsyncResult is added to m_asyncmethods.
This fixes issue #294.

Fix a race condition with all async methods.

---

FluentFTP/Client/FtpClient_HighLevel.cs

Related with issue https://github.com/robinrodricks/FluentFTP/issues/308
In a multiplatform app for UWP and Android that shares assemblies for accesing ftp code I found that for the same files (of approximattely 6 MB each file) and same server (Filezilla server) the UWP app doesn't fails downloading  those files, but Android app fails almost every time with this exception:  IOException "Unexpected EOF for remote file ..." https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Client/FtpClient_HighLevel.cs#L1814
Problem could be caused by this behavior of the java bytecode to which is translated C# in a xamarin code: https://wiki.sei.cmu.edu/confluence/display/java/FIO10-J.+Ensure+the+array+is+filled+when+using+read%28%29+to+fill+an+array
Initially I tried to fix it with the …

Fixes Many Unexpected EOF for remote file IOException on Android

---

FluentFTP/Client/FtpClient_Connection.cs

In this PR the Dispose method of the FtpClient is made virtual. This makes it possible to add custom dispose logic in an inherited class. So far I have overriden the virtual Disconnect method. But I think making the dispose method virtual is more accurate.

Make Dispose method of FTPClient virtual

---

FluentFTP/Client/FtpClient_HighLevel.cs
FluentFTP/Helpers/FtpEnums.cs

Added new upload option to AppendNoCheck so that we can append a file on the server without checking if it exists yet.  This is required if the server you are uplaoding to does not allow you to list the contents of the folder, but the file does exist.
The call will throw an exception when the NLIST command is used, this will bypass the exception since we are not checking the directory for the file.

Added new upload option to AppendNoCheck so that we can append with no check.

---

FluentFTP.Examples/AsyncConnect.cs
FluentFTP.Examples/Examples.csproj
FluentFTP.Examples/Main.cs
FluentFTP/Client/FtpClient_Connection.cs
FluentFTP/Client/FtpClient_Hash.cs
FluentFTP/Client/FtpClient_HighLevel.cs
FluentFTP/Client/FtpClient_Listing.cs
FluentFTP/Client/FtpClient_LowLevel.cs
FluentFTP/Client/FtpClient_Management.cs
FluentFTP/Client/IFtpClient.cs
FluentFTP/Proxy/FtpClientHttp11Proxy.cs
FluentFTP/Proxy/FtpClientProxy.cs
FluentFTP/Stream/FtpSocketStream.cs

Since there is no way to cancel an async Read on a Socket, this PR adds a way to cancel the read via CancellationTokens. Even so it does pass the CancellationToken to the Async Read, the Socket doesn't care about it at all. That's why we catch the CT right before the ReadAsync and link it to a new tokensource which is triggered based on ReadTimeout.
If that tokensource triggers it closes the stream and catches the Exception that might occure. Depending on the tokensource that caused the exception either a TimeoutException or a CanceldException is thrown (or if the error is not caused by a CTS, then the exception is rethrown.
The main Timeout handling code is here:
https://github.com/robinrodricks/FluentFTP/pull/377/files#diff-0ee804b19786cb587081edeb1a65dc72R504
Also this PR adds …

Add Cancellation Token support and async timeout

---

FluentFTP/Stream/FtpSocketStream.cs

This swaps the stream order of SslStream and BufferedStream, so that instead of SslStream->BufferedStream->NetworkStream the order becomes BufferedStream->SslStream -> NetworkStream.
This fixes a regression from #355 where proxied connections with FtpClientHttp11Proxy are unable to connect.
Failing example:
```
var proxyCredentials = new NetworkCredential("username", "password");
var proxyInfo = new ProxyInfo { Host = "1.2.3.4", Port = 5000, Credentials = proxyCredentials };
var ftpCredentials = new NetworkCredential("ftpuser", "ftppassword");
using (var client = new FtpClientHttp11Proxy(proxyInfo) { Host = "ftphost", Port = 990, Credentials = ftpCredentials, EncryptionMode = FtpEncryptionMode.Implicit })
{
client.Connect();
}
```
The call to `Connect()` times out during read if the the …

Swap SslStream and BufferedStream

---

FluentFTP/Client/FtpClient_Connection.cs
FluentFTP/Helpers/FtpExceptions.cs

Issue 399, use a sub-class of the old exception for authentication errors. That way it is possible to catch and not retry them. Opted for quick solution to get this in place fast.

#399 Use specific "auth failed" exception

---

FluentFTP/Client/FtpClient_FileManagement.cs

GetFileSize always returns 0 instead of the FileSize out of sizeReply.

Fixed Synchronous GetFileSize always returning 0

---

FluentFTP/Client/FtpClient_HighLevelDownload.cs
FluentFTP/Client/FtpClient_HighLevelUpload.cs
FluentFTP/Client/FtpClient_Properties.cs

The original rate control is too rough for me, so I improved the rate control of the high level API.
Note that transferChunkSize may be changed internally to optimize the low rate limit.

improve rate control for high level API

---

FluentFTP.Examples/AsyncConnect.cs
FluentFTP.Examples/BeginConnect.cs
FluentFTP.Examples/BeginCreateDirectory.cs
FluentFTP.Examples/BeginDeleteDirectory.cs
FluentFTP.Examples/BeginDeleteFile.cs
FluentFTP.Examples/BeginDereferenceLink.cs
FluentFTP.Examples/BeginDirectoryExists.cs
FluentFTP.Examples/BeginDisconnect.cs
FluentFTP.Examples/BeginExecute.cs
FluentFTP.Examples/BeginFileExists.cs
FluentFTP.Examples/BeginGetFileSize.cs
FluentFTP.Examples/BeginGetListing.cs
FluentFTP.Examples/BeginGetModifiedTime.cs
FluentFTP.Examples/BeginGetNameListing.cs
FluentFTP.Examples/BeginGetWorkingDirectory.cs
FluentFTP.Examples/BeginOpenAppend.cs
FluentFTP.Examples/BeginOpenRead.cs
FluentFTP.Examples/BeginOpenWrite.cs
FluentFTP.Examples/BeginRename.cs
FluentFTP.Examples/BeginSetWorkingDirectory.cs
FluentFTP.Examples/Connect.cs
FluentFTP.Examples/CreateDirectory.cs
FluentFTP.Examples/CustomParser.cs
FluentFTP.Examples/DereferenceLink.cs
FluentFTP.Examples/Extensions.cs
FluentFTP.Examples/GetListing.cs
FluentFTP.Examples/Rename.cs
FluentFTP.Examples/SetEncryptionProtocols.cs
FluentFTP.Examples/SetWorkingDirectory.cs
FluentFTP/Helpers/FtpListParser.cs

- Fix typos
- Remove unused namespaces
- Sort used namespaces
- Remove unnecessary delegate creations
- Fix Tests project build error

Minor fixes in examples

---

FluentFTP/Client/FtpClient_Hash.cs

This pull requests solves the issue submitted in [Ticket #478 (Cannot verify MD5 hash when file name contains spaces when using egnyte.com)](https://github.com/robinrodricks/FluentFTP/issues/478). 
As per https://tools.ietf.org/html/draft-twine-ftpmd5-00#section-3.1, the MD5 Command Output is expected to be in a following format:
`251 [FilePath] E67DED2886048D308532042B777D53CF`
If the file path contains spaces (e.g. `file 1.xlsx`), the response might be represented in a following way:
`251 "/shared/import/file 1.xlsx" 48317576D6CA6C93641CCB06487AF457`. In such case, the response parsing of the MD5 Command is not taking into account the additional quotes around the `[FilePath]`, hence the HashVerification process fails prematurely. 
Changes in this pull request take into account the …

Verification of the MD5 Hash when file name contains spaces.

---

FluentFTP/Client/FtpClient_LowLevel.cs

The 172.2 pattern has an extra \ causing the fallback to host ip not to occur

Fix for non-routable IP regex

---

FluentFTP/Client/FtpClient_Stream.cs
FluentFTP/Streams/FtpSocketStream.cs

Hi robinrodricks -
There's a handle leak that occurs each time I call FluentFTP.FtpClient.Connect(). (I'm also calling Disconnect() and Dispose(), after each Connect().) It leaks a few hundred handles each time, and these leaked handles accumulate over time, until my app stops working. (I don't need to get a file list, or to download a file, to get this leak; I only need to Connect().)
It only leaks handles when it's able to connect to the FTP server (if the FTP server is down it won't leak handles). I tested using FileZilla FTP server, locally, with loopback IP address 127.0.0.1, and also using a remote FTP server. (Also, I ran my app (the FTP client) on two different computers, and I turned off my firewall, to make sure it wasn't interfering.) The handle leaks still occurred.
These …

Close (Dispose) AsyncWaitHandles to stop handle leak (in .NET Framework 4.5 build)

---

FluentFTP/Streams/FtpSocketStream.cs

Use of hard-coded 'checkCertificateRevocation' parameter value to SslStream's 'AuthenticateAsClientAsync' method was replaced with the 'ValidateCertificateRevocation' property as a fix for #493, but async version of the code was omitted.

Fix 'ValidateCertificateRevocation' property not being used in async version

---

FluentFTP/Client/FtpClient_Connection.cs
FluentFTP/Proxy/FtpClientBlueCoatProxy.cs
FluentFTP/Proxy/FtpClientUserAtHostProxy.cs

Fixes #642
Logs after fix:
```
Status:   Connecting to ***
Response: 220 *** FTP server (Version 1.9.2.1 - 2003/05/11 20:39:33) ready.
Command:  USER ***
Response: 331 Password is required
Command:  PASS ***
Response: 332 Account is required
Command:  ACCT ***
Response: 230 ***Logon ok
Command:  FEAT
Response: 500 'FEAT': command unrecognized.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 UNIX Type: L8
Command:  PWD
Response: 257 "***" is the current directory.
```

respect `332 Need account for login` response during authorization

---

FluentFTP/Client/FtpClient_Utils.cs

Encountered an infinite loop when connecting.
Debugging shows that the ReadStaleData function was closing the connection, resulting in a connection attempt being made (from Execute()), which repeats endlessly.
For the particular FTP server I was connecting to it appears that the only stale data was the newline character.
ReadStaleData actually already trims off the newline characters when building the string to log out, so we can easily check if that string in empty in order to determine if we really need to close the stream for that "stale" data.
Once that change was made, connections to the server were successful.

fix ReadStaleData causing infinite loop

---

FluentFTP/Client/FtpClient_FXPFolderTransfer.cs
FluentFTP/Client/FtpClient_FileProperties.cs
FluentFTP/Client/FtpClient_FolderDownload.cs
FluentFTP/Client/FtpClient_FolderManagement.cs
FluentFTP/Client/FtpClient_Listing.cs
FluentFTP/Client/IFtpClient.cs
FluentFTP/FluentFTP.csproj

Support IAsyncEnumerable on .NET Standard 2.0+, so users no longer need to wait the complete listing operation to finish.
Example usage:
```csharp
using System;
using FluentFTP;
var ftpClient = new FtpClient("ftp://ftp.aist-nara.ac.jp");
await ftpClient.AutoConnectAsync();
await foreach (var i in ftpClient.GetListingAsync("/", FtpListOption.Recursive))
{
Console.WriteLine(i.FullName);
}
```

Support IAsyncEnumerable on .NET Standard 2.0+

---

FluentFTP/Client/FtpClient_FileUpload.cs
FluentFTP/Client/FtpClient_Utils.cs
FluentFTP/Helpers/FileListings.cs

@robinrodricks 
There is an issue when attempting to upload files to servers running zOS MVS as FluentFTP only accounts for Windows and UNIX-like file structures.
My proposed changes will check for the FTP Server Type and FTP OS Type where available. It will also check if the path specified starts with a single quote as this is indicative of a full qualified directory when using data sets. Then will adjust the target paths for the remote accordingly.
These changes should leave the behavior for Windows/UNIX-like systems unchanged while allowing file uploading to zOS MVS servers.
Please let me know what you think of these changes!

Bugfix for file uploading via FTP to IBM zOS Server running MVS.

---

FluentFTP/Client/FtpClient_FileUpload.cs

An issue with my previous implementation is that it is assuming you are always trying to upload to a PO (Physical Organization) and would throw the error "Unable to upload, use MVS naming convention" when trying to upload to other locations.. So I only fixed half the problem.
By just sending the filename into the STOR command rather than with the full file path, the STOR command is intelligent enough to determine if the target location is a Physical Organization and append the (filename) convention to upload to a Partitioned Data Set. It also can append the .filename convention if it is a Physical Sequential location and upload it like a normal file rather than a PDS.

Fixed IBM zOS MVS File uploading

---

FluentFTP/Client/FtpClient_Stream.cs

I think I found the problem in my case. Azure Web App have multiple IP's for the same host and the list always failed when the IP changed suddenly from one to another:
See [Incorrect directory listing on "Failed to connect to host" exception](https://github.com/robinrodricks/FluentFTP/issues/723)

Issue_723 - Possible wrong IP on command EPSV

---

FluentFTP.Tests/Tests.cs
FluentFTP/Client/FtpClient_Listing.cs

Fixes regression from "sanitize all input paths" / restores behavior from version 34.0.2.

#768 Listing methods where parameter "path" may be null will now use Working Directory instead of "/"

---

FluentFTP/Client/FtpClient_FileManagement.cs
FluentFTP/Client/FtpClient_Listing.cs

These small changes will allow the bool FileExists(...) function to work for IBM z/OS

Minor server specific changes for IBM zOS: bool FileExists(....)

---

FluentFTP/Client/FtpClient_Listing.cs
FluentFTP/Client/FtpClient_Properties.cs
FluentFTP/Enums/FtpParser.cs
FluentFTP/Enums/FtpServer.cs
FluentFTP/Enums/FtpzOSListRealm.cs
FluentFTP/Helpers/FtpListParser.cs
FluentFTP/Helpers/Parsers/FtpIBMOS400Parser.cs
FluentFTP/Helpers/Parsers/FtpIBMzOSParser.cs
FluentFTP/Servers/Handlers/IbmOs400FtpServer.cs

Robin,
Here is my current take on getting GetListing(...) to work with z/OS (and OS/400, which is unchanged and just separated out from the "generic" IBM label).
Some other functions of FluentFTP will still **not** work, especially those that rely on path manipulation etc., unless you are moving in the z/OS USS realm - this is sufficiently unix-like.
I see some places where others have already fixed upload and download for native z/OS dataset names (like "`'HLQ.QUAL1.QUAL2'`"),  those very valuable fixes handle the case of a fully complete dataset specification and I have been happily uploading and downloading thanks to those.
To show the user a list of items to choose from, this PR concerns getting a sensible listing of the available dataset / files under the current directory.
I wanted …

Support z/OS and OS/400 GetListing Function

---

FluentFTP/Client/FtpClient_AutoConnection.cs
FluentFTP/Exceptions/FtpInvalidCertificateException.cs

This one is hard to explain:
If:
You use autoconnect
and
You decide to use the `OnValidateCertificate` delegate
and
You decide to **REJECT** the certificate...
the current logic will notice the failure and attempt a disconnect, which will attempt a "QUIT" execution, which will percolate an outstanding exception, which makes everything following this very unclean.
I feel that a successful connection that fails due to a rejected certificate should terminate the sequence of connections attempts, and furthermore, do this in a more graceful fashion.
My 2 cents on this, so I submit this for review and discussion.
As with all other PRs I am using these ASIS for a z/OS - Unix FTP navigator.

Better handling of not-accepted certificates on autoconnect

---

FluentFTP/Client/FtpClient_Listing.cs

When connected to a FEAT MLST / MLSD server, the parser is set to "machine".
If you now specify FtpListOptions.ForceList, one would expect this to **take precedence** over the "machine" setting of the parser.
You absolutely need this if you are interested in seeing entries that are _links_ - these are not supported by the MLSD "machine" parser, for understandable reasons (see [this](https://www.rfc-editor.org/errata/eid1500) to realise that MLST might be very nice and fast, easier to parse, but sadly it currently does not support link entries in a standardized way.

FtpListOption.ForceList is not being honored

---

FluentFTP/Client/FtpClient_Listing.cs

**urgent**
GetListing() works but PR 764 causes very many unneccessary parse fail warnings.
An `else` keyword somehow disappeared on the commit/push sequence.

Fix GetListing() regression caused by PR #764 - many untrue parse fail warnings

---

FluentFTP/Client/FtpClient_Listing.cs

This change prevents the Modified date of a FtpListItem being overwritten if the consecutive MDTM command fails.

Fix unwanted Modified date overwrite.

---

FluentFTP/Client/FtpClient_Connection.cs

Re-using a client instance to connect to a server with different capabilites is possible but the `FEAT` command is not performed on the new connection. This causes problems when the new server has **LESS** features than the previous server. Unless it is a cloned connection.
Simple solution is to clear the capabilites list if it is not a clone.

Re-use of client instance to server with different capabilities

---

FluentFTP/Client/FtpClient_FolderManagement.cs
FluentFTP/Client/FtpClient_Stream.cs

In the `GetWorkingDirectory()` and `SetWorkingDirectory()` API function code logic, there is a `_LastWorkingDir` that acts as "cache" to avoid repeated `PWD` commands to the server. This is set to `null` when a connect takes place. Also set to `null` when a `SetWorkingDirectory()` is done.
So far so good.
But the `Execute(....)` API function could also perform a CWD. This is "coming from outside" and plays havoc on the internal cwd cache. This is especially if z/OS users CWD like crazy to do their thing and then expect GetCurrentDirectory to tell the truth.
Thus, I propose setting `_LastWorkingDir` to `null` in the execute routine if the command is a CWD. This makes the `null` setting in `SetWorkingDirectory()` redundant since it calls `Execute(CWD...)`. 
In a nutshell, **anyone, from …

Catch CWD in Execute to invalidate cwd cache

---

FluentFTP/Client/FtpClient_FolderManagement.cs
FluentFTP/Enums/FtpzOSListRealm.cs

This is a new API function.
When writing a nice FTP Client GUI for file system navigation in z/OS, one comes across the problem of "What is the z/OS realm of the filesystem path described by the current working directory".
For a unix like filesystem, the realm is of course unix and such a function is not needed.
But for a z/OS, a specialised function can make things easier.
The currrent working directory on z/OS either begins with a `/`, which tells us: realm is HFS.
Otherwise, it must be one of the z/OS (aka MVS) realms. But which one?
Short of doing a LIST command (which would be one way to do this), this makes use of a nice z/OS FTP server feature: When you `CWD` to an arbitrary path, if that path denotes a partitioned dataset, your are told that this is the case. And even more …

GetzOSListRealm() API function

---

FluentFTP/Helpers/RemotePaths.cs

Together with the (small) code changes for #786 and #787, there is a quite large block of code needed for IBM z/OS, to calculate `.FullName` in `GetListing(....)` entries for the different scenarios of using `GetListing(...)` with or without `FtpListOption.NoPath` in the different `zOSListingRealm`s.
So this PR contains the needed code for the **whole** fix. The previous PR's (#786, #787) are solely to explain the "collateral" damage when trying to  fixup `CalculateFullFtpPath()`.
It contains the smaller amounts of code for #786, #787 **plus** this large block of IBM z/OS code, which 
looks like this:
```
if (client.ServerType == FtpServer.IBMzOSFTP &&
client.ServerOS == FtpOperatingSystem.IBMzOS &&
client.zOSListingRealm != FtpZOSListRealm.Unix)
{
// The user might be using …
```

CalculateFullFtpPath final Code + Wiki update

---

FluentFTP.Tests/Tests.cs
FluentFTP/FluentFTP.csproj
FluentFTP/Proxy/FtpClientSocks5Proxy.cs
FluentFTP/Proxy/Socks/SocksEnums.cs
FluentFTP/Proxy/Socks/SocksProxy.cs
FluentFTP/Proxy/Socks/SocksProxyException.cs

#82 Adding unauthenticated SOCKS5 proxy support.
Changes include adding an implementation of a SOCKS proxy following the RFC : https://datatracker.ietf.org/doc/html/rfc1928
Tested against VSFTPD using Dante as a SOCKS proxy, both locally and against an Azure installation, where the FTP was running on a local address.
Commands to spin up a local copy for testing:
`docker run -d --restart=always -p 9020:20 -p 9021:21 -p 9100-9110:9100-9110 -e FTP_USER=ftp -e FTP_PASS=ftp -e PASV_ADDRESS=172.18.144.1 -e PASV_MIN_PORT=9100 -e PASV_MAX_PORT=9110 -v /data/ftp:/home/vsftpd fauria/vsftpd`
`docker run -d -p 1080:1080 wernight/dante`
Example usage can be found in the test project.

#82 - Implement No Auth SOCkS proxy 

---

FluentFTP/Helpers/Parsers/FtpIBMzOSParser.cs

Discovered this one listing files under "SYS1.".
It is very minor, has no huge consequences. But for the sake of getting it right... very big files will overflow on the size calculation resulting in negative file sizes. We are talking about `ntracks * 56664` overflowing `int`. But, can happen, as I saw.

z/OS Parser: Big files, do not want negative file sizes

---

FluentFTP/Client/FtpClient_Listing.cs

Recently updated issue #751 describes the case where `path` can be `null`, thus causing an exception to be thrown.
So, rearranging the OR clause and adding a `null` check to fix this.

Fix Regression #751 due to IBM z/OS changes

---

FluentFTP/Helpers/FtpListParser.cs
FluentFTP/Helpers/Parsers/FtpIBMzOSParser.cs

This is missing from previous PR #788. The consequences of this omission are that you still need to CWD to the place where you want to do GetListing, if you are listing a directory of a non-RECFM=U PDS.
My mistake, sorry, dunno how it got lost.

z/OS parser modification was omitted in #788

---

FluentFTP/Client/FtpClient_FileDownload.cs
FluentFTP/Client/FtpClient_FileProperties.cs
FluentFTP/Client/FtpClient_IBMzOS.cs
FluentFTP/Model/FtpProgress.cs

Thanks to the previous merges, here are (more or less) the last changes:
----
`FtpClient_FileProperties.cs`
If a z/OS server reports "SIZE" capability, things go wrong in case of z/OS realm datasets. Because other than in the HFS realm, no size is available. On the other hand, if it does not report the "SIZE" capability, we can **still** obtain a size due to the previous changes we made. So let's do it ourselves... ==> ignore SIZE capability, even if the z/OS FTP server is thus configured.
...but this then means:
`FtpClient_FileDownload.cs`
Since we have a size now (however we acquired it) on z/OS files (whichever realm), but this size is **not** accurate (see wiki), we need to `readToEnd` = `true` ==> this means **act** like `fileLen` is zero.
----
`FtpClient_IBMzOS.cs`
Since the last …

z/OS: Consolidation and some further (small) changes

---

FluentFTP/Client/FtpClient_FileDownload.cs
FluentFTP/Client/FtpClient_FileUpload.cs

An IOException as a result of a connection interruption resulted in the data streams not being closed

Streams not disposed in case of an IOException

---

FluentFTP/Client/FtpClient_Stream.cs

This PR is a reiteration of #805, concerns `OpenRead(...)`
I closed that to research some other problems and to isolate a number of other things to look at, but am putting this back in now.
SInce the changes for z/OS, the `GetFileSize(...)` which is performed prior to the `RETR` will (in case of z/OS) perform a `GetListing(...)` to determine the file size. But this will issue a `SetDataType(...)` for `TYPE I`. This will counter the `SetDataType(...)` for `ASCII` that a user might have requested.
This is not an old problem. It was introduced by the z/OS changes (and only happens for z/OS servers).
It means that a z/OS server cannot be told to perform an `ASCII` transfer unless this is merged.

SetDataType DIRECTLY before the RETR

---

FluentFTP/Client/FtpClient_Connection.cs

This should fix #812 where `m_IsAuthenticated` is not updated by `AuthenticateAsync`.

Fix #812 : IsAuthenticated is not updated when calling ConnectAsync

---

FluentFTP/Client/FtpClient_Stream.cs

This PR concerns `SetDataType(...)`:
In the log, I was surprised to see so many unneeded "`TYPE I`" commands, even though there is a caching mechanism (similar to the one for "`CWD`" / "`PWD`").
It turns out that some callers (rightly) go in at `...NoLock(...)`, thereby bypassing the cache.
This PR moves the caching code down into the no-lock part of the code. The diff looks crazy, I know, maybe lay the two versions side by side :-)

Stop some callers from bypassing the CurrentDataType cache

---

FluentFTP/Servers/FtpServerSpecificHandler.cs

This PR concerns `DetectFtpOSBySyst(...)`:
Someone reported that after connecting to his z/OS CS FTP server, he cannot access the z/OS realm.
It turns out FluentFTP recognizes the system as being "UNIX".
Research showed up the following:
There is a parameter for the IBM z/OS CS FTP server called "STARTUPDIRECTORY" (see [here](https://www.ibm.com/docs/en/zos/2.4.0?topic=protocol-startdirectory-ftp-server-statement#strtdir)).
It was set to "HFS", which causes the `SYST` command to respond like this:
`215 UNIX is the operating system of this server. FTP Server is running on z/OS.`
Up to now we have only been expecting:
`215 MVS is the operating system of this server. FTP Server is running on z/OS.`
Both of these texts contain the needed "`Z/OS`" (ToUppered...), but the `if` clauses trigger …

z/OS FTP Server SYST command replies differently depending on realm

---

FluentFTP/Client/FtpClient_Connection.cs
FluentFTP/Client/FtpClient_FileDownload.cs
FluentFTP/Client/FtpClient_FileManagement.cs
FluentFTP/Client/FtpClient_FileProperties.cs
FluentFTP/Client/FtpClient_FileUpload.cs
FluentFTP/Client/FtpClient_FolderManagement.cs
FluentFTP/Client/FtpClient_IBMzOS.cs
FluentFTP/Client/FtpClient_Listing.cs
FluentFTP/Client/FtpClient_Utils.cs
FluentFTP/Helpers/RemotePaths.cs

Trying to clean up some of my previous z/OS contributions.
Checking for `ServerType == FtpServer.IBMzOSFTP` **and** `ServerOS == FtpOperatingSystem.IBMzOS` is totally redundant.
A check for `ServerType == FtpServer.IBMzOSFTP` is sufficient.

Checking for FtpOperatingSystem.IBMzOS is redundant

---

FluentFTP/Client/FtpClient_Stream.cs
FluentFTP/Client/IFtpClient.cs

**Concerns the OpenRead, OpenAppend, OpenWrite group of methods**
In response to [this](https://github.com/robinrodricks/FluentFTP/pull/819#issuecomment-1013114436).
The changes to the last version caused the following problem:
For these methods, the param `checkIfFileExists` no longer exists. It is replaced by `fileLen` with a similar logic, but enhanced by _one more_ possibility.
One user immediatly responded, he was able to circumvent, but there may be more out there who **do not intend** to change their code to replace a `true` / `false` by either `0`or `-1`, respectively.
Perhaps it would be a good idea to bring back the old methods so any users out there will not be hurt. And to have **one new** method with the `fileLength` instead of the `checkIfFileExists`, which can be called by …

Bring back original OpenXXX methods as documented in Wiki and ADD the new ones instead

---

FluentFTP.Tests/Tests.csproj
FluentFTP/Client/FtpClient_Properties.cs
FluentFTP/FluentFTP.csproj

I was wondering why the `netstandard2.0`, `netstandard2.1` and `net5.0` targets had so many explicit dependencies as most/all of them are included in the respective BCLs.
This PR cleans that up.
According to `dotnet list .\FluentFTP\FluentFTP.csproj package --vulnerable --include-transitive` the changes from this PR still respects the request from #624 about not depending on the vulnerable `System.Net.Security 4.3.0`.
As the net50 target no longer defines `NETFX` or `NET45` these methods change behavior.
I have not looked into whether the new behavior is desired.
* `FtpClient.GetPublicIP`
* `FtpClient.StartListeningOnPort`
* `FtpSockStream.RawSocketReadAsync`
* `FtpSockStream.AcceptAsync`

Cleanup dependencies

---

FluentFTP/Servers/FtpServerSpecificHandler.cs

This fixes #766. Works for both formats now. Tested on my proFTPd. 
BTW: As opposed to the statements of OP in #766, this is actually **not'' turned on in the server config by default.
At least, for Debian it was actually turned **on** by default (a mistake) which was corrected on 14 Aug 2020. By now (on Debian 11) it is fixed.
See [here](https://github.com/proftpd/proftpd/issues/1085)

Handle possible multiline FEAT reply format

---

FluentFTP/Client/FtpClient_Stream.cs

This should fix #842. Once again fell into the trap of a missing ASYNC duplicate of a change.

Invalidate PWD cache in ASYNC code also, this was missing

---

FluentFTP/Client/FtpClient_Hash.cs
FluentFTP/Servers/FtpBaseServer.cs
FluentFTP/Streams/FtpFileStream.cs

The `async` keyword makes the compiler add a bunch of code to create the underlying state machine that drives asynchronous methods in C#.
You can see [here](https://sharplab.io/#v2:D4AQTAjAsAUCAMACEECsBuWsQGZlkQGFYBvWRC5PEADmQDYAeAIwHtWAbAPkQEEBnAJ4A7AMYBpAKaCA7qwBOAEwAUASnKUyMSjuQB2RADMAhh36TM2ygF8NFO1QYt23BgDF5rALYAlSfwBXDgAXNQctXUoQAxB6ADoPbz9AkOUTM0lVSx1bGFzYIA==) what the compiler generated code is.
For a longer explanation of the difference, see e.g https://stackoverflow.com/questions/52146203/async-method-with-no-await-vs-task-fromresult

Use Task factory methods instead of going `async`

---

FluentFTP/Client/FtpClient_Connection.cs
FluentFTP/Client/FtpClient_FXPFileTransfer.cs
FluentFTP/Client/FtpClient_FXPVerification.cs
FluentFTP/Client/FtpClient_Properties.cs

Some places the arguments to `ArgumentNullException` and `ArgumentOutOfRangeException` where incorrect.
The constructors are defined as follow:
* `public ArgumentNullException (string paramName)`
* `public ArgumentNullException (string paramName, string message)`
* `public ArgumentOutOfRangeException(string paramName)`
* `public ArgumentOutOfRangeException(string paramName, string message)`

Some ArgumentExceptions take `paramName` as the first parameter

---

FluentFTP/Servers/Handlers/NonStopTandemServer.cs
FluentFTP/Servers/Handlers/OpenVmsServer.cs
FluentFTP/Servers/Handlers/WindowsCeServer.cs
FluentFTP/Servers/Handlers/WindowsIisServer.cs

Child classes of `FtpBaseServer` does not properly override `GetParser` using `override`.
The implication is that the value of `FtpBaseServer.GetParser()` is returned if the child class is casted to `FtpBaseServer`.
Here's an [example](
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoa0gAiLIHZqBvauzhkkjr9qlyF0AClACWeDDCgAKPDADudAGrioGHAEMANgHEYGEVqgBnGbICUlgNx9hoiVIsLlAeQBuMiQBMYBoxNzOWs7QS4AX2p7BjIkBhRHSWk5ADEMAAcAIS1zAGUZLyg6YKLLGIEHTkYATllSmQA6AIAVAE8MmCtGgDktAFsYOgBqOgAiEHGRhqhmw2MzC1CYqKpV6hg8HH66dIyF4LYYnPM0GIBhAAtxHR9qdap6PZOYAqgio/DqgGY6D3VNLpdpkDjI6AFQSE6ABeAB8wP2QSaLzCD3oag02n08yRxUmz1yr0KMk+QiIv3+mKBe0h4JxiyhcIRkMaVxuPlR0UeJDonm84j8ENxdHxmRebw+VEqXHJdAgRV8QxpwqFDKsMPhyoZrOut1RQA===) that shows the problem.

Change virtual to override for GetParser

---

FluentFTP/Helpers/Parsers/FtpIBMzOSParser.cs

When the number of tracks used by a z/OS Dataset exceeds "99999" (i.e. 5 digits), the size is depicted as "+++++". This caused the size calculation to fail for obvious reasons. (Exception). In this case we use the absolute maximum size that is possible for a single volume dataset, which of course is an abominable overestimation, thanks IBM for such a stupid limit of 5 chars for the "Used" collumn.
```
//Volume Unit    Referred Ext Used Recfm Lrecl BlkSz Dsorg Dsname   
//ANSYBG 3390   2020/01/03  1   15  VB   32756 32760  PS  $.ADATA.XAA
//ANSYBH 3390   2022/02/18  1+++++  VBS  32767 27966  PS  $.BDATA.XBB
```

z/OS GetListing(): Handle "+++++" in Used collumn

---

FluentFTP/Servers/Handlers/IbmZosFtpServer.cs

Since moving this to the server specific handler, needs to handle z/OS unix realm as well. Also the z/OS realm was not handled correctly in all cases.

Fix z/OS IsRoot() and some comment typos

---

FluentFTP/Client/FtpClient_FileUpload.cs

I've had a couple of uploads fail today with the error "File does not exist". I'm using the UploadFiles() function to upload a bunch of files at once. Since I didn't see any way of retrieving a list of failed files, my approach is to filter the log for messages and create my own list.
Regarding the problem itself: I suppose it's an issue with a path being too long (running the code on a Windows system). Since I can only access the system during certain times, I can't provide any more details at the moment. I'll open a separate issue if necessary.
Feel free to adjust my changes if necessary.

Added localPath to log message

---

FluentFTP/Helpers/Hashing/HashParser.cs

This fixes a bug that won't allow a correct checksum for files with whitespaces in their name (or in parent directories)

Fix regex for files with whitespaces

---

FluentFTP/Client/FtpClient_Stream.cs

When trying to open a data stream if client.EncryptionMode=Auto client.DataConnectionEncryption=true and AUTH TLS is rejected, a significant delay occurs followed by an IOException - "Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
Reproduced the error by setting up a FileZilla server and turning off TLS and then trying to connect with the conditions above and trying to call UploadFile().
Async calls are unaffected as they already have the "&& !_ConnectionFTPSFailure" test.
**Workaround:**
I have worked around this issue in production by turning off DataConnectionEncryption manually.
``` …
```

Fixes IOException in synchronous methods when AUTH TLS is rejected

---

FluentFTP/Servers/FtpServerStrings.cs

SIZE command does't work in case when FTP server replies with messages in Russian.
FTP Server: ProFTPD on CentOS 7 with LANG=ru_RU.utf8
Verbose: >         AutoConnectAsync()
Verbose: >         AutoDetectAsync(True, False)
Verbose: >         ConnectAsync()
Info: Status:   Connecting to 127.0.0.1:21
Info: Response: 220 FTP Server ready.
Info: Command:  AUTH TLS
Info: Response: 500 AUTH не распознано
Info: Command:  USER test
Info: Response: 331 Необходим пароль для пользователя test
Info: Command:  PASS ***
Info: Response: 230 Пользователь test подключён
Info: Command:  FEAT
Verbose: Response: 211-Features:
Response: MFF modify;UNIX.group;UNIX.mode;
Response: REST STREAM
Response: MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
Response: UTF8
Response: EPRT …

Support russian variant in FtpServerStrings.fileSizeNotInASCII

---

FluentFTP.sln
FluentFTP/FluentFTP.csproj
FluentFTP/Proxy/FtpClientSocks5Proxy.cs
FluentFTP/Proxy/Socks/SocksProxy.cs
SOCKS5.Test/Program.cs
SOCKS5.Test/SOCKS5.Test.csproj

Our use case needed username/password authentication against a SOCKS5 proxy.
We realized that the previous pull request did not implement RFC1929.
https://datatracker.ietf.org/doc/html/rfc1929
We saw where/how it was not doing it correctly, and implemented RFC1929 as best as we could.
Then we tested in a separate project (in our dev-environment, we only care about .net core 3.1) and tested the private resources we were working with. Then confirmed everything was working, and prepared this pull request.
Let us know if you have any questions.
Thanks.

SOCKS5 Support with Username/Password Authentication

---

.github/workflows_WIP/pull_request.yml
FluentFTP.Tests/DockerCollection.cs
FluentFTP.Tests/Integration/IntegrationTestSuite.cs
FluentFTP.Tests/Unit/TimeoutTests.cs
FluentFTP.Xunit/Attributes/Internal/SkippableTheoryDiscoverer.cs
FluentFTP.Xunit/Attributes/SkippableFactAttribute.cs
FluentFTP.Xunit/Attributes/SkippableTheoryAttribute.cs
FluentFTP.Xunit/Docker/Containers/CrushFtpContainer.cs
FluentFTP.Xunit/Docker/Containers/FileZillaContainer.cs
FluentFTP.Xunit/Docker/Containers/GlFtpdContainer.cs
FluentFTP.Xunit/Docker/Containers/ProFtpdContainer.cs
FluentFTP.Xunit/Docker/Containers/PureFtpdContainer.cs
FluentFTP.Xunit/Docker/Containers/PyFtpdLibContainer.cs
FluentFTP.Xunit/Docker/Containers/VsFtpdContainer.cs
FluentFTP.Xunit/Docker/DockerFtpContainer.cs
FluentFTP.Xunit/Docker/DockerFtpServerFixture.cs

Correct namespace for SkippableAttributes.
Correct chaining of TestcontainerBuilder.
Change Fixture to CollectionFixture.
Refactor timeout test.
Add SocketException to accept criteria (occurs when running in GitHub Actions).
This PR is a few fixes to get the TestcontainersBuilder back to working in new structure.
Change Fixture to CollectionFixture, from ClassFixture, to keep the same container instance running for all test classes.

Configure containers.

---

FluentFTP.Tests/Integration/IntegrationTests.cs
FluentFTP.Tests/Integration/System/IntegrationTestRunner.cs

Bugfix observe exceptions from async tests.
Since the Task.Run was not awaited the tests would ignore exceptions.
Changed tests to async Task to remove need for Task.Run and instead await the tests directly.

Catch errors in async tests.

---

FluentFTP/Client/IFtpClient.cs

Being a total noob to this library, I found myself in need having the CompareFIle & CompareFIleAsync in IFtpClient for unit testing purposes.
I could not find any reasons why the should not be there. If there are please enlighten me :)
I had som issues running all integrationtests, even prior to making any change - but I believe that this is related to #903

#910 Add CompareFile & CompareFIleAsync to IFtpClient

---

FluentFTP.Dockers/vsftpd/Dockerfile
FluentFTP.Tests/Integration/System/IntegrationTestRunner.cs
FluentFTP.Xunit/Docker/DockerFtpServer.cs

Make Dispose wait for completion to avoid starting next container before the previous is shut down.
Add finalizer to call Dispose if an exception is thrown in constructor.

Make vsftpd Dockerfile work

---

FluentFTP/Servers/Handlers/IbmZosFtpServer.cs

Refactoring of `IbmZosFtpServer.cs`:
Small oversight/typo, discovered on further testing.
`ConvertListingPath` was never being called. Thus, file sizes were only correct for z/OS unix files.

Fix fix #909

---

FluentFTP/Client/Modules/ServerModule.cs

The order of these statements is important:
```
else if (system.Contains("Z/OS")) {
// IBM z/OS, message can be one of the two, depending on realm (and server config)
// Syst message: "215 MVS is the operating system of this server. FTP Server is running on z/OS."
// Syst message: "215 UNIX is the operating system of this server. FTP Server is running on z/OS."
//**
//** Important: Keep this z/OS IN FRONT of the UNIX entry, both contain "UNIX".
//**
serverOS = FtpOperatingSystem.IBMzOS;
}
else if (system.Contains("UNIX") || system.Contains("AIX")) {
// Unix OS
serverOS = FtpOperatingSystem.Unix;
}
```
One could change the UNIX test to `Contains("UNIX") && !Contains("z/OS")` to make the statements independant of the order, maybe?

Important comment

---

FluentFTP/Client/FtpClient_FileManagement.cs
FluentFTP/Client/FtpClient_Listing.cs
FluentFTP/Client/FtpClient_Utils.cs
FluentFTP/Servers/FtpBaseServer.cs
FluentFTP/Servers/Handlers/IbmZosFtpServer.cs

This gives us a `IsCustomGetAbsolutePath()` query **INSIDE** the regular `GetAbsolutePath()` and thus eliminates a lot of `if (ServerHandler...` code outside.
**Note:** The regular `GetAbsolutePath(...)` **still** contains a second ServerHandler function, `IsAbsolutePath(...)` which was created for **OpenVMS**. This can probably be migrated to the new custom mechanism, but since I cannot test it, I have left it in place for the time being.
The functionality of `IsAbsolutePath(...)` sadly was not sufficient to also use for z/OS, although it looked promising at first, early simple tests actually worked, but not all special cases.
There was also some "old" z/OS (MVS) code in there that has been redundant for some time.
An additional benefit of this change, is that **all** callers of …

Eliminate redundant ServerHandler queries

---

FluentFTP/Client/FtpClient_FileManagement.cs
FluentFTP/Client/FtpClient_FileUpload.cs
FluentFTP/Client/FtpClient_Utils.cs
FluentFTP/Helpers/FtpListParser.cs
FluentFTP/Helpers/RemotePaths.cs
FluentFTP/Servers/FtpBaseServer.cs
FluentFTP/Servers/Handlers/IbmZosFtpServer.cs
FluentFTP/Servers/Handlers/OpenVmsServer.cs

This change finalizes my attempts to move the z/OS logic to a ServerHandler. Once you get some practice (on the previous ones), you can move faster... Success!
Added ServerHandler(s):
For `FtpClient_FileManagement`
**FileExists(..)**
`ServerHandler.DontUseSizeEvenIfCapable`
`ServerHandler.DontUseMdtmEvenIfCapable`
`ServerHandler.IsCustomFileExists`
`ServerHandler.FileExists`
For `FtpClient_FileUpload`
**UploadFiles(..)**
More or less complete rewrite of the path/directory handling logic so to use the new ServerHandlers and the following new ones:
`GetAbsoluteDir()`
`GetAbsoluteFilePath()'
For `FtpListParser`
`ServerHandler.IsCustomCalculateFullFtpPath`
`ServerHandler.CalculateFullFtpPath`
and so on and on.. it is a lot, I realize, but quite systematic:
1. A number of new serverhandler …

Rest of the changes

---

FluentFTP/Servers/Handlers/IbmZosFtpServer.cs

#928 is fine but I discovered this type that needs to be fixed. 
It causes the `item.FullName` to be incorrect for any z/OS GetListing.

z/OS Listing FullName sometimes incorrect

---

FluentFTP/Client/AsyncClient/UploadDirectory.cs
FluentFTP/Proxy/AsyncProxy/AsyncFtpClientSocks4Proxy.cs
FluentFTP/Proxy/AsyncProxy/AsyncFtpClientSocks4aProxy.cs

Found some places, where the `CancellationToken` parameter was not passed along to inner async calls.

Forward cancellation token

---

FluentFTP/Streams/FtpSocketStream.cs

Issue: https://github.com/robinrodricks/FluentFTP/issues/763
Accrording to this [acrticle](https://www.suse.com/support/kb/doc/?id=000020678) in order to correctly receive response on upload status from vsftpd servers data connection should be closed using SSL_Shutdown command. This functionality has always been present, but it never kicked in due to dispose order in FtpSocketStream dispose logic. When ssl stream given DisconnectWithShutdown is set to true tried to shutdown SSL Stream underlying stream was already disposed which throwed exception swollowed inside dispose method.

Fixed issue with 426 error for vsftpd servers

---

FluentFTP/Streams/FtpSocketStream.cs

** Active Mode, cannot reuse the ActivePorts **
Please refer to the excellent problem description on #954
Accepting on a listening socket creates a **new** socket. The previous code simply took over the new socket, literally leaving the listening socket sitting there, still listening, for eternity, thus it was no longer eligible when the next request tried to select an available socket.
The new approach is to close this listening socket after accepting from it.
Surprisingly, a shallow copy of the socket suffices to be able to do this.
Passes the intergration tests.

Fix issue 954

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs

I believe this fixes #961, but I haven't tried it out.
When `OpenRead` throws an exception `downStream` isn't assigned to a non-null value.
This causes a `NullReferenceException` when trying to dispose it.
The exception is immediately caught but that has two drawbacks.
* It's much more expensive to throw and catch an exception than null checking it.
* As reported in the issue it breaks the IDE when a debugger is attached and `NullReferenceException` is checked in "Exception Settings".

Add null checks when disposing

---

FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs

Please see the tail end of Issue #858 
After adding the needed code, I realised that a refactor of `UploadFileInternal` would optimise the use of the SIZE command **not only** for the case when `NoCheck` is requested, but **also** for the case when `OverWrite` is active.
Here is what it now looks like if `Overwrite` is requested (only one SIZE command, previously there were **two!**):
```
>         UploadFile("D:\temp\test1", "/home/mike/test1", Overwrite, False, None)
>         FileExists("/home/mike/test1")
Command:  SIZE /home/mike/test1
Response: 550 /home/mike/test1: No such file or directory
>         OpenWrite("/home/mike/test1", Binary)
>         OpenActiveDataStream(PORT, "STOR /home/mike/test1", 0)
Command:  PORT 192,168,1,147,31,146
Response: 200 PORT command successful …
```

Optimize SIZE command usage for UploadFile NoCheck AND OverWrite (Issue #858)

---

FluentFTP.Tests/Unit/ExceptionTests.cs
FluentFTP/Exceptions/FtpCommandException.cs

Thanks @jnyrup for your patience with this. Dunno why you didn't PR this yourself - as I had seen empty FtpCommandExceptions myself I decided I would like this too.
Adding a test is of course totally the icing on the cake and I copy/pasted that from you too.
@robinrodricks Depends on you to feel happy with this new message format:

Fix/Enhance #704 Consider including Code in FtpReply Message

---

FluentFTP/Streams/FtpSocketStream.cs

I find this very useful when debugging connects.
Show protocol in the FTPS authentication successful message. Change some upper case to lower case at the same time.
```
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 AUTH TLS successful
Status:   FTPS Authentication Successful, protocol = Tls12
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,0030331.
```

Show protocol in Auth Success message

---

FluentFTP/Client/AsyncClient/Authenticate.cs
FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/BaseClient/ReadStaleData.cs
FluentFTP/Client/SyncClient/Authenticate.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs

This is a simple addition to `ReadStaleData` which does not change very much.
Each call to this method is garnished with an additional string parameter so that in verbose logging, you can see from where it has been called.
More importantly, it decides to not use the raw socket for cleaning any stale data if encryption is turned on. 
With encryption turned on, this would be destructive in random (but quite often) occurring cases.
This change is not risky. It needs to be in place before I can put in the next one, for `GetReply`, because there is a dependancy.

Next step: Read stale data

---

FluentFTP/Client/SyncClient/Connect.cs

Maybe I am blind, so someone else also have a lool at this. I just stumbled accross it.
```
reply = Execute("AUTH TLS");
if (!reply.Success) {
Status.ConnectionFTPSFailure = true;
if (Config.EncryptionMode == FtpEncryptionMode.Explicit) {
throw new FtpSecurityNotAvailableException("AUTH TLS command failed.");
}
}
else if (reply.Success) {
m_stream.ActivateEncryption(Host, Config.ClientCertificates.Count > 0 ? Config.ClientCertificates : null, Config.SslProtocols);
}
```

Redundant If

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Proxy/AsyncProxy/AsyncFtpClientSocks4Proxy.cs
FluentFTP/Proxy/AsyncProxy/AsyncFtpClientSocks4aProxy.cs
FluentFTP/Proxy/AsyncProxy/AsyncFtpClientSocks5Proxy.cs
FluentFTP/Proxy/Socks/Socks4Proxy.cs
FluentFTP/Proxy/Socks/Socks4aProxy.cs
FluentFTP/Proxy/Socks/SocksProxy.cs
FluentFTP/Servers/Handlers/IBMzOSFtpServer.cs
FluentFTP/Streams/FtpSocketStream.cs

Found some places where a `CancellationToken` was not passed along.
The changes in PR only changes method signatures that are not publicly exposed.
These methods do not take a `CancellationToken` but call a method that does take a `CancellationToken`, but I didn't change them as they are public.
* `PurgeSuccessfulUploadsAsync` -> `DeleteFile`
* `ResumeDownloadAsync` -> `OpenRead`
* `ResumeUploadAsync` -> `OpenAppend`
* `ActivateEncryptionAsync` -> `AuthenticateAsClientAsync`
* `GetFilesToTransfer` -> `GetFileSize`
* `FtpSocketStream.AcceptAsync` -> `Socket.AcceptAsync`

Forward CancellationToken in async calls

---

FluentFTP/Client/SyncClient/Connect.cs
FluentFTP/Streams/FtpSocketStream.cs

Disable of SSL Buffering helped a lot for NOOP handling. But the current implementation disable the buffering **also** for the data connection.
That is not needed. It is enough the disable buffering **only** on the control connection.

Disable buffering ONLY on the control connection

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/AsyncClient/OpenActiveDataStream.cs
FluentFTP/Client/AsyncClient/OpenPassiveDataStream.cs
FluentFTP/Client/SyncClient/Connect.cs
FluentFTP/Streams/FtpSocketStream.cs

OpenActiveDataStream Sync/Async
OpenPassiveDataStream Sync/Async
Connect Sync/Async
FtpSocketStream : ActivateEncryption Sync/Async
Sorry, sort of got into a slight conflict here with you @jnyrup, on your token propagation. I did some reordering, removed some unused overloads and fixed up all the references.
Thanks also for reminding me of "Named Parameters". Should use them more often.

Clean up parameters / signatures

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs

This is a very very dirty quick fix for those servers (.NET 6.0, vsftpd) that can't seem to want to relinquish their pent up NOOP responses **until the next command** comes along, which brings commands and responses out of sync.
It fixes the NOOP problems of vsftpd with .NET 6.0+

Causer server hickup, release pending responses

---

FluentFTP/Helpers/Parsers/IBMzOSParser.cs
FluentFTP/Servers/Handlers/IBMzOSFtpServer.cs

Try to use LISTLEVEL 2. Parser understands all LISTLEVELs, so no mind if the z/OS is too old and stays on LISTLEVEL 0. 
This will give a better size resolution on huge files. Remember the '+++++' problem, because the Size column was not wide enough?
214-LISTLEVEL={0|1|2} Specifies the format of the LIST reply.  LISTLEVEL 0
214-                specifies that PDS, PDSE and HFS data sets are displayed
214-                with a DSORG value of PO.  LISTLEVEL 1 specifies that PDS
214-                data sets are displayed with a DSORG value of PO, PDSE
214-                data sets are displayed with a DSORG value of PO-E, and
214-                HFS data sets are displayed with a DSORG value of HFS.
214-                LISTLEVEL 2 specifies LISTLEVEL 1 display options, and
214- …

Switch to using LISTLEVEL 2, filesize more exact

---

FluentFTP/Client/AsyncClient/GetListing.cs
FluentFTP/Client/SyncClient/GetListing.cs
FluentFTP/Enums/FtpListOption.cs
FluentFTP/Enums/FtpZOSListRealm.cs
FluentFTP/Helpers/Parsers/IBMzOSParser.cs

Issue #747: Please read (especially at the end) or in the Wiki: [here](https://github.com/robinrodricks/FluentFTP/wiki/IBM-zOS-and-OS-400-Support#accessing-the-jes2-internal-reader-to-submit-batch-jobs-and-how-to-list-and-retrieve-job-output)
Added `FtpZOSListRealm.Jes2`.
Added the capability to parse this realm.
Needed to add a listing option to deter `GetListing(...)` from switching to `Image`, we need this process to stay in `ASCII`.

Make #747 happy: Add LIST functionality for z/OS JES subsystem

---

FluentFTP/Client/AsyncClient/GetListing.cs
FluentFTP/Client/SyncClient/GetListing.cs
FluentFTP/Enums/FtpListOption.cs

No further comment, apart from:
Use
`FTP_Sess.Config.ListingDataType = FtpDataType.ASCII;`
instead.

Take back FtpListOption.NoImage. Not needed

---

FluentFTP/Client/BaseClient/GetReply.cs
FluentFTP/Client/BaseClient/Properties.cs

Fixes (as an enhancement) https://github.com/robinrodricks/FluentFTP/issues/747
There is now a List<FtpReply> LastReplies with max 5 elements.
The previous LastReply still exists - it is fed from LastReplies[0]. If you want the next reply previous to that, you need LastReplies[1] and so on.
Especially useful to access intermediate messages on download (RETR) and upload (STOR) commands

Keep a (short, n=5) list of previous replies.

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/AsyncClient/SetDataType.cs
FluentFTP/Client/BaseClient/BaseFtpClient.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/BaseClient/Properties.cs
FluentFTP/Client/SyncClient/Connect.cs
FluentFTP/Client/SyncClient/SetDataType.cs
FluentFTP/Enums/FtpDataType.cs
FluentFTP/Helpers/Parsers/IBMzOSParser.cs
FluentFTP/Model/FtpClientState.cs
FluentFTP/Servers/Handlers/IBMzOSFtpServer.cs

`Status` was created to keep status information for the session, so why not move `CurrentDataType` to that substructure.
At the same time, if it inits to `Unknown` we can do away with the `ForceSetDataType`.
Also, a bug fixed: If a user executes a `TYPE` command, `CurrentDataType` goes out of sync. Happily, no one really does this, right?
Sometime in the future, issue a STAT command after connect and parse per server, set the initial value from there

Move CurrentDataType to Status and remove ForceSetDataType

---

FluentFTP/Client/BaseClient/GetReply.cs
FluentFTP/Model/FtpReply.cs

When debugging complex problems, it can be usefull to examine `LastReplies[n]`. These will also now contain the command associated with this reply.

Store the associated command together with the reply.

---

FluentFTP.Tests/Unit/ParserTests.cs
FluentFTP/Helpers/Parsers/IBMOS400Parser.cs

IBM OS400 filenames can contain blanks.
Motivated by #994

IBM OS400: Support blanks in filename, add unit test for that

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/BaseClient/Logger.cs
FluentFTP/Client/SyncClient/Connect.cs

This might help in case users are secretive
```
...
Status:   Waiting for response to: SYST
Response: 215 UNIX emulated by FileZilla.
Status:   Listing parser set to: Machine
Status:   Connection established by FluentFTP Version 41.0.0.0
...
```

Show FluentFTP version in log after connect

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/GetReply.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/BaseClient/GetReply.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/GetReply.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs

This concludes the step by step `GetReply` redesign **provoked by the `NOOP` issues**.
V41 introduced rudimentary quick fixes to get things going, but for V42 a better structured approach is in order.
What are the main differences:
`GetReply` now has two operating modes:
1. **Normal mode**, as before - which is a blocking mode that can timeout, raise an exception.
2. **"**exhaust NOOP**" mode**, **new** - this mode is not blocking, it waits 10 seconds to gather all replies on the connection. It also provokes many servers to make stale data finally appear on the connection by issueing a `NOOP` command. This way, a legitimate ensuing command won't be compromised.
This new mode implements the suggestions mentioned [in this discussion](https://lists.apache.org/thread/xzpclw1015qncvczt8hg3nom2p …

GetReply Redesign

---

FluentFTP/Streams/FluentSslStream.cs
FluentFTP/Streams/FtpSocketStream.cs

Send your own close notify. See #996.
This wraps SslStream, takes Dispose and goes into marshalled unsafe code to produce an encrypted message to send on the socket that will be decrypted on the server that then reads correctly as an alert to close notify.
Note: When (someday) TLS 1.3 is taken a step further and this might have been fixed by MS, one might need to programmatically disable the sending of the close notify unless TLS 1.2 is being used.

FluentFTP wrapper for SslStream

---

FluentFTP/Streams/FluentSslStream.cs
FluentFTP/Streams/FtpSocketStream.cs

The SSL Closure Alert should **always** be sent.

Make SSL Shutdown independant of Config.DisconnectWithShutdown

---

FluentFTP/Streams/FtpSocketStream.cs
FluentFTP/Streams/FtpSslStream.cs

1. Go back to a better naming of the SSL wrapper (`FtpSslStrem` etc.)
2. Disregard the setting of `Config.DisconnectWithShutdown`. The parameter remains in `Config` but is ignored. An API change is deferred until some more have accumulated. Wiki will reflect this
3. Remove .NET 5+ code in FtpSslStream, but keep it as comments in case it is ever needed.

Ongoing changes for SSL Shutdown

---

FluentFTP/Streams/FtpSocketStream.cs

Interesting to note that the socket shutdown logic causes timeouts to fail - nobody has ever seen this happen, when `Config.DisconnectWithShutdown` was set to true.

Remove Socket Shutdown logic, not needed

---

FluentFTP/Model/FtpConfig.cs
FluentFTP/Streams/FtpSocketStream.cs

A SSL Closure Alert is now always sent when a stream is "terminated". The Socket will get a Dispose. CloseSocket will be renamed to DisposeSocket. This is also to a certain degree for #996.

CloseSocket->DisposeSocket and remove Config.DisconnectWithShutdown

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs

Whilst searching/checking for correctness of our integration tests, it was a nice quick way to confirm the downloads/uploads were doing what they were supposed to do when changing the lengths and size of the data.

More verbose messages to help debugging

---

FluentFTP.Dockers/proftpd/run-proftpd.sh
FluentFTP.Dockers/proftpd/tls.conf
FluentFTP.Dockers/vsftpd/run-vsftpd.sh
FluentFTP.Dockers/vsftpd/vsftpd.conf
FluentFTP.Tests/Integration/IntegrationTests.cs
FluentFTP.Tests/Integration/System/IntegrationTestRunner.cs
FluentFTP.Xunit/Docker/Containers/ProFtpdContainer.cs
FluentFTP.Xunit/Docker/Containers/VsFtpdContainer.cs
FluentFTP.Xunit/Docker/DockerFtpContainer.cs
FluentFTP.Xunit/Docker/DockerFtpServer.cs

Those servers capable of this (currently vsftpd and proftpd) can be run from a single docker image, a single docker file etc. as either an FTP or an FTPS server. This is controlled by an environment variable (`$USE_SSL`).

Ability to run test server containers as FTP or FTPS servers

---

FluentFTP.Dockers/Build.bat
FluentFTP.Dockers/Build.sh
FluentFTP.Dockers/bftpd/Dockerfile
FluentFTP.Dockers/bftpd/bftpd.conf
FluentFTP.Dockers/bftpd/docker-compose.yml
FluentFTP.Dockers/bftpd/run-bftpd.sh
FluentFTP.Tests/Integration/IntegrationTests.cs
FluentFTP.Xunit/Docker/Containers/BfFtpdContainer.cs
FluentFTP.Xunit/Docker/DockerFtpContainerIndex.cs

Lets add another test server.
This one was interesting: Due to a bug it has (it is not an impressive server, to be honest), it uses up its passive port range and then fails. This is why in this docker container the passive port range is **a little bit larger**, otherwise the tests fail.

Add bftpd test server

---

FluentFTP.Dockers/bftpd/Dockerfile
FluentFTP.Dockers/proftpd/Dockerfile
FluentFTP.Dockers/vsftpd/Dockerfile

...by using a two stage build debian bullseye-slim
bftpd **450MB** --> **150MB**, others save 150MB or so.

Drastically reduce some test server image sizes

---

FluentFTP.Tests/Unit/ParserTests.cs

In a future PR I will change the code to reference the right year automatically.

Fix date related parser test fail. But better solution is on Todo list.

---

FluentFTP.Dockers/Build.bat
FluentFTP.Dockers/Build.sh
FluentFTP.Dockers/filezilla/Dockerfile
FluentFTP.Dockers/filezilla/docker-compose.yml
FluentFTP.Dockers/filezilla/run-filezilla.sh
FluentFTP.Dockers/filezilla/settings.xml
FluentFTP.Dockers/filezilla/users.xml
FluentFTP.Tests/Integration/IntegrationTests.cs
FluentFTP.Xunit/Docker/Containers/FileZillaContainer.cs
FluentFTP.Xunit/Docker/DockerFtpContainerIndex.cs

FileZilla integration test server

---

FluentFTP.Dockers/bftpd/Dockerfile
FluentFTP.Dockers/filezilla/Dockerfile
FluentFTP.Dockers/glftpd/Dockerfile
FluentFTP.Dockers/proftpd/Dockerfile
FluentFTP.Dockers/vsftpd/Dockerfile

To reduce build times, use a python script to select the debian mirror for the apt build steps

Select fastest nearby debian apt mirror automatically

---

FluentFTP.Xunit/Docker/Containers/PureFtpdContainer.cs

Instead of brutally enabling "ALL", why not just enable those that are **actually** needed...

Better granularity on CAP settings for pure-ftpd

---

FluentFTP/Streams/FtpSocketStream.cs

socket.Poll and the poll interval have been subject of numerous discussions and some false/outdated information in the issues.
When studying the code, this saves some time when doing research on this.

Just an important comment

---

FluentFTP/Client/AsyncClient/GetReply.cs
FluentFTP/Client/BaseClient/GetReply.cs

In preparation for fixing #1030 - fix reconnect problems
The log message should appear before the possible throw

Log first, then perhaps throw

---

FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/AsyncClient/GetReply.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/BaseClient/GetReply.cs

In preparation for fixing #1030 - fix reconnect problems
Cleaning the command to be logged is a separate functionality from updating stored values, which should only happen on command success
Cannot do the command cleaning in this block:
```
if (reply.Success) {
OnPostExecute(command);
}
```

Separate clean command and postexecute functionality

---

FluentFTP/Model/FtpClientState.cs

In preparation for fixing #1030 - fix reconnect problems
When connecting with the same client, status is reset - but it was missing the ASCII/BINARY information to be reset.

Reset was missing CurrentDataType

---

FluentFTP/Client/BaseClient/Execute.cs

Nobody should ever do this, but if a CWD **without any parms or just blanks** is generated, different servers will react differently. 
- a server might refuse and reply with an error code without changing the current working directory
In this case, this code won't even get entered. It only runs on command success.
In case of a command success :
- z/OS or some other servers will go to the users home dir or to the root dir
-  a server might ignore the CWD command without changing the current working directory
So, let's set the current working directory stored value to **null** in this case.

Update CWD to null on special case of CWD command

---

FluentFTP/Model/FtpConfig.cs
FluentFTP/Streams/FtpSocketStream.cs

Fixes #1035 
Also, it brings in some other missing stuff in the async section of Connect.
In the sync section, I tried to make the behaviour for a timeout value of 0 behave the same way as in the async section, which means take the internal socket timeout (about 21 seconds). Otherwise a timeout of 0 would return immediately w/o a connection.
Also, the code to fix #869 was somewhat flaky. Generally, I would refrain from using error texts (in possibly hundreds of different language variants) and try to use socket error codes. Testing for the error text and the error code is also quite redundant.
Also implemented @robinrodricks suggestion:
> A suggestion - what if we moved the main connection part into a new subroutine, and then called that from within the "addresses" loop. That way the …

Complete overhaul of connect code

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/SyncClient/Connect.cs
FluentFTP/Streams/FtpDataStream.cs
FluentFTP/Streams/FtpSocketStream.cs

To help debugging, it is useful to know **which** stream is suddenly being disposed.
The needed flag for `IsControlConnection`: First I set that in `connect()`, but later on I realised it would be much cleaner to put that into the stream constructor.
A very nice side effect of adding this flag was to take back the parameter passing of the `isControlConnection` flag in the `CreateBufferStream` process.

Better log message for stream dispose

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs

ResumeDownload Sync and Async look good, but they are missing the try catch that can be seen in ResumeUpload Async,
ResumeUpload Sync is missing, although there is a ResumeUpload Async.
1. Make a nice try catch aggregate exception (using ResumeDownloadAsync as a model) in the other three cases
2. Code the missing ResumeUpload for Sync using the others as a model.
3. Add a log message so that the resume operation is actually noticed by users

Make resume logic the same for upload/download sync/async

---

FluentFTP/Client/BaseClient/Execute.cs

The assumption that a CWD command sets the current working directory to the string behind the command was a brain shortcircuit.
Set to null is the way to go.

Revert the CWD update change

---

FluentFTP/Model/FtpClientState.cs
FluentFTP/Streams/FtpSocketStream.cs

This solves two problems:
1. A large amount of DNS request can be issued on connect in some situations. This can cause a rejection by the DNS server as protection against a DOS attack.
It can happen when you issue a lot of connects using the same client,
or
when you issue commands that cause a lot of data connections using PASV against local non-routable addresses.
2. All connections to the server should use the same firstly issued DNS query answer, even if the server is multi-interfaced and different DNS replies are issued.
The cache lives as long as the client instance.

DNS Caching

---

FluentFTP.Dockers/bftpd/Dockerfile
FluentFTP.Dockers/filezilla/Dockerfile
FluentFTP.Dockers/glftpd/Dockerfile
FluentFTP.Dockers/proftpd/Dockerfile
FluentFTP.Dockers/pureftpd/Dockerfile
FluentFTP.Dockers/vsftpd/Dockerfile

In some locations there are not enough mirrors to allow python smart-apt to generate a sources.list for debian without throwing an error. The author seems unresponsive. Therefore using this very valueable method to make a docker build process run **significantly** faster is not viable.
Here is the step back down to the default debian sources.list and **rather** slow central repo.
Tested and runs.

Dockerfiles: No mirror optimisation

---

FluentFTP/Streams/FtpSocketStream.cs

In case a source compile targets NET Framework 4.6.2, as reported in #1054, there is a compile error.
It used to be in the old code, I had removed it when working on the connect timeouts.
Of course, just using the nuget package will work fine, but those of us who need to use the source might like this to be fixed.
Merging this is optional IMO, but perhaps for the sake of completeness one should include this in the code.

Cater to #1054

---

FluentFTP/Client/AsyncClient/Authenticate.cs
FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/BaseClient/ReadStaleData.cs
FluentFTP/Client/SyncClient/Authenticate.cs

`ReadStaleData(...)` shouldn't be the one who closes the connection. This decision belongs into `Execute(...)`, which is the only place where the "reconnection" boolean is ever seen as being true.
So, removing this parameter and making this decision in `Execute(...)` (next PR).

Prepare for ReConnect PR

---

FluentFTP/Client/AsyncClient/GetReply.cs
FluentFTP/Client/BaseClient/GetReply.cs

Example of one that was **not** recognized: `200 Command NOOP okay.` Yet again a new format.
All previous formats were `200 NOOP.......` or `200 Noop.....`.

Accept more formats of NOOP messages

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs

In case an unexpectedly early `226 Transfer complete` message appears, finish the transfer instead of later on going into an endless wait for a response.

Fix #1059 Early 226 Success Message

---

FluentFTP/Client/AsyncClient/GetListing.cs
FluentFTP/Client/SyncClient/GetListing.cs

This should hopefully fix #1080.
An alternative would be to catch the failure of the EPRT, PORT, PASV etc. failure, i.e. `OpenActiveDataStream`s or `OpenPassiveDataStream`s failure to open such a stream.

Catch control connection loss and retry once

---

FluentFTP/Client/AsyncClient/Execute.cs

Simple fix. The AsyncFtpClient still does not redirect calls.
```
void IInternalFtpClient.DisconnectInternal() {
// TODO: Call DisconnectAsync
}
void IInternalFtpClient.ConnectInternal() {
// TODO: Call ConnectAsync
}
void IInternalFtpClient.ConnectInternal(bool reConnect) {
// TODO: Call ConnectAsync
}
```
This is still a todo item since V40 refactor, so this fix to workaround for now.

Fix #1082 (Re)Connect goes to nirvana

---

FluentFTP/Client/AsyncClient/OpenDataStream.cs
FluentFTP/Client/SyncClient/OpenDataStream.cs

These connects are actually reconnects **some time before a command** because the socket info is needed.

These are reconnects!

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/AsyncFtpClient.cs
FluentFTP/Client/BaseFtpClient.cs
FluentFTP/Client/FtpClient.cs
FluentFTP/Client/Interfaces/IAsyncFtpClient.cs
FluentFTP/Client/Interfaces/IFtpClient.cs
FluentFTP/Client/Interfaces/IInternalFtpClient.cs

This will make the interface implementations for ConnectInternal and DisconnectInternal complete for Async.
Any internal client calls to Connect and Disconnect will need these. They were missing for Async.
ConnectInternal can only be used in the `Connect....(bool reConnect.....)` mode. There is no need for a `Connect()` underload.

Fix the Connect/Disconnect InternalClient calls

---

FluentFTP/Client/Modules/ConnectModule.cs

`client.ValidateCertificateHandlerExists == null` is a typo. Boolean == null is always false.
Merge with outer if statement and correct the typo:
`profile.Encryption != FtpEncryptionMode.None && client.ValidateCertificateHandlerExists == false`
Much better.

Boolean! Compare to false and not to null.

---

FluentFTP.Tests/Unit/ParserTests.cs

`FtpListItem?[]?` looks crazy, but it is a nullable ref value consisting of nullable list items. Finally gets rid of all nullability warnings in `ParserTests.cs`

Yet another "nullable" improvement

---

FluentFTP/Streams/FtpSocketStream.cs

This is needed to make the maximum Ssl commands reached - reconnect work.

ReadLineCount++ was missing!

---

FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/SyncClient/Connect.cs

No need to issue a new `FEAT` command on reconnect. Save some bandwidth, just like with clone.
If the CWD is null for some reason (for example, if just previously, there was a CWD command), there would be no CWD to return to on reconnect, which is erroneous.
So, in such a case the CWD is retrieved by issuing one last command: A PWD via `GetWorkingDirectory/Internal`. To avoid an infinite recursive loop, the reconnect criteria are reset before doing this.

Handle edge case and save bandwidth on automatice/forced reconnect

---

FluentFTP/Client/AsyncClient/GetListing.cs
FluentFTP/Client/BaseClient/IsProxy.cs

Visual Studio warned that `AsyncFtpClient` could never be of type `FtpClientSocks4Proxy` or `FtpClientSocks4aProxy`.
I have not tested this is any way.

Check for async proxy

---

FluentFTP.Tests/Unit/IsProxyTests.cs

Some parts of this library are more difficult to tests, but the changes in #1113 are easy-peasy to test, so here goes.

Add unit tests of `IsProxy()`

---

FluentFTP/Client/AsyncClient/Disconnect.cs
FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/DownloadFiles.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/AsyncClient/UploadFiles.cs
FluentFTP/Client/AsyncClient/VerifyTransfer.cs
FluentFTP/Client/BaseClient/Logger.cs
FluentFTP/Client/Interfaces/IInternalFtpClient.cs
FluentFTP/Client/SyncClient/Disconnect.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/DownloadFiles.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFiles.cs
FluentFTP/Client/SyncClient/VerifyTransfer.cs
FluentFTP/Streams/FtpSocketStream.cs

Many logging frameworks separate the logging message from any other data, e.g. exceptions.
In visualization of logs logging message and exception then have separate columns.
This is similar to how parameterized SQL queries separates the query from the parameters.
Also for `ILogger`s it should not be necessary to explicitly prefix the logging message with the loglevel, as that is controlled in the logging format template.
E.g. for [serilog](https://github.com/serilog/serilog/wiki/Formatting-Output)

Logging exceptions

---

FluentFTP/Streams/FtpSocketStream.cs
FluentFTP/Streams/FtpSslStream.cs

See issue #1107.
This improves handling of auth exceptions a little bit.
It also fixes what seems to be an incorrect way to close down an ssl stream - leading to an IOException after a numer of ssl shutdowns.

Bring in the changes made to Fix/Improve for issue 1107

---

FluentFTP/Streams/FtpSocketStream.cs

@jnyrup So, look at this, if I rearrange the catch I can have a single common one at the end.
Too bad I cannot bring in the `ObjectDisposedException` as well, as it is encased in the outer #else-#endif

Further optimise follow up for #1124

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/SyncClient/Connect.cs

It would "sort of" work, but fail in other places.  --> Revert back to an implicit Connect().
This happens when a user has not used Connect() (Or AutoConnect()) yet, but attempts to issue an API command, I did this by mistake today, and this would recognize that we are not connected and attempt a re-connect. This re-connect would for example fail to do a FEAT command and other stuff, causing unexpected results. Thus, in such a case, revert back to a normal full fledged connect.
I added a log message to show this happening.
Instead of adding a flag in Status, I just used the IP-Address internal cache having at least on entry. In case we ever invalidate that cache based on DNS time to live data, we would need to use a flag.
So @robinrodricks, should we use a flag?
Also, in case of …

Do not attempt Reconnect if we have not ever been connected before.

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/SyncClient/Connect.cs

In addition to restoring the current working directory, one needs to restore the ASCII/BINARY data type setting on a reconnect.
Noticed this when I saw a reconnect happening on a failed GetFileSize command. The SIZE command (and many others) are sensitive to the DataType setting, which is reset to ASCII on many servers after a fresh connect.

Improve reconnect logic

---

FluentFTP.Logging/FluentFTP.Logging.csproj
FluentFTP/FluentFTP.csproj

You can't set both and expressions are better because it allows tools to automatically determine the license.
Also fix the copyright (copied from LICENSE.TXT)

Use expression instead of file for NuGet license

---

FluentFTP/Client/AsyncClient/GetCommandOutput.cs
FluentFTP/Client/SyncClient/GetCommandOutput.cs

See the issue #1195 
Add a way to issue arbitrary commands - and retrieve their output from the data connection, if they happen to do that.
Exotic systems sometimes have such commands (beyond the usual suspects like STOR, RETR, LIST, etc.) that we know nothing about.
This API call gives the user a way to access the output of such commands.
Note: This is for retrieving Line-by-line based text output. It is not for binary data in the current version and not meant as any kind of replacement for regular download operations.
Issue #1195 (look at the trailing end of the issue) gives us an example of such a functionality.

GetCommandOutput

---

FluentFTP/Client/SyncClient/DiscoverSslSessionLength.cs

As suggested by you, @robinrodricks, this API function will issue  up to `maxTrys=2000` commands `command="PWD"` with an inter-command delay of `delay=50` to help the user find out the recommended setting of `SslSessionLength` fot this server connection.
Usage:
```cs
ftpClient.Connect();
Console.WriteLine("Set SslSessionLength to less than: " + ftpClient.DiscoverSslSessionLength());
```

DiscoverSslSessionLength

---

FluentFTP/Client/BaseClient/GetPassivePort.cs

Ever since (some months ago) we have a DNS cache, where we store the SINGLE IPAD that we have successfully connected to, even if the server has multiple IP Addresses, we can rely on our own connect logic to pick up this **same** IPAD again on EPSV requests.
So therefore, the previous fix, by getting the IPAD from the socket endpoint, is no longer needed. Trouble was: On EPSV, this broke the proxy connect logic, where the proxy expects a DNS name and cannot make head not tail of the socket endpoint IP address.
Fixes issue #1205

Issue #1205 Repair logic to support proxy connections

---

FluentFTP/Streams/FtpSocketStream.cs

Consistent log message order when handling exception. Discovered this discrepancy during debugging a different problem.

Logging tweak: Message first, then close, same as in SslStream part

---

FluentFTP/Client/AsyncClient/GetListing.cs
FluentFTP/Client/AsyncClient/GetObjectInfo.cs
FluentFTP/Client/AsyncClient/GetZOSListRealm.cs
FluentFTP/Client/BaseFtpClient.cs
FluentFTP/Client/SyncClient/GetListing.cs
FluentFTP/Client/SyncClient/GetObjectInfo.cs
FluentFTP/Client/SyncClient/GetZOSListRealm.cs
FluentFTP/Model/FtpReply.cs

I can't tell the flow of what happens, but if we hit one of these `breaks` in `GetReplyInternal` we could skip writing to `reply.InfoMessages`.
Supersedes #1235.

More null checks of `Reply.InfoMessages`

---

FluentFTP/Client/BaseClient/Logger.cs

```
>         AutoConnect()
>         AutoDetect(True, False)
>         Connect(False)
Status:   FluentFTP 46.0.2.0(.NET 6.0)
Status:   Connecting to IP #1= ***:21
```
FluentFTP is a multi targeted library. Currently net50, net60, net462, net472, netstandard2.0, netstandard2.1.
You reference it using your code/your target. But which one is chosen by Nuget? Or by you? It should always be a compatible one, that's pretty sure, but it is nice to know which one was considered suitable, since inside FLuentFTP, different things may happen depending on target.
This does not prove or show what .NET target is in effect in the code of the assembly referencing FluentFTP, but can help gathering information when problems occur.

Show build target on connect

---

FluentFTP/Enums/FtpsBuffering.cs
FluentFTP/Model/FtpConfig.cs
FluentFTP/Streams/FtpSocketStream.cs

Update all the config texts and other place to reflect the actual behaviour of the config parameters.
Since a year or so, "Auto" and "On" have effectively been the same. We have **always** turned **off** SslBuffering in special cases, even if the user had specified "On".
The special cases are:
- Under .NET 5.0 and later due to platform issues (see issue 682 in FluentFTP issue tracker).
- On the control connection
- For proxy connections
- If NOOPs are configured to be used

SSL Buffering: Update explanatory texts and refactor slightly

---

FluentFTP/Streams/FtpSslStream.cs

I decided to clean up the conditional compiles and check each one for validity.
It turns out that .NET Framework supports ShutDownAsync since .NET 4.7 ( !!! ) which we somehow didn't really see so clearly at the time.
Therefore the only one of our build targets left over would be .NET 4.6.2, which needs the ugly reflection hack to send a close notify.
**BUT** Beware: .NET Standard 2.0 **also does not have this capability** which means theoretically we should develop the same hack for this target as for .NET 4.6.2. So I added that.
If this ever becomes an issue for someone, this will be needed.
I stumbled across this whilst searching for solution to #1251 
Read this:
Here is a quote from: https://github.com/dotnet/standard/issues/598#issuecomment-352148072
"The SslStream.ShutdownAsync API …

Tidy up the conditional compiles and test for each target in FtpSslStream.cs

---

FluentFTP/Helpers/Hashing/HashParser.cs

BrickFTP (files.com / Exavault.com) responds in a non - standard fashion (no filename).
Changed the regex to handle that situation.
Incidentally: The fix for #722 (which was never confirmed) which attempts to remove "213" from the server response as a fix is obsolete (the server response code is removed prior to the call of this function anyway) and not the real reason why #722 was reported. #722 was **another, first** occurrence of **"missing" filename**. And lo and behold, it was the same server type as the one reported here.

Fix for #1286

---

FluentFTP/Client/Modules/ConnectModule.cs

This is a regression introduced (by me, alas) some time ago and it causes a premature termination of the AutoDetect logic whenever SSL Authentication (i.e. switching to encrypted traffic) fails.
There will be some more separate changes to AutoDetect in the course of further testing re. issue #1289

Fix regression: Premature AutoDetect termination

---

FluentFTP.Logging/FluentFTP.Logging.csproj
FluentFTP.Tests/FluentFTP.Tests.csproj

Integration test involving FluentFTP.GnuTLS were failing.
43.0.1 -> 47.0.0 and 1.0.5 -> 1.0.20 and also lib version 3.7.8 -> 3.8.0

FluentFTP nuget updates needed to run our integration tests

---

FluentFTP.Logging/FluentFTP.Logging.csproj
FluentFTP.Tests/FluentFTP.Tests.csproj

This reverts commit f3cad9000a35a336688bec68c496901f7771fd06.
It was only supposed to change FluentFTP.Tests, not Logging also. I need to redo this.

Revert "FluentFTP nuget updates needed to run our integration tests"

---

FluentFTP.Tests/FluentFTP.Tests.csproj

Integration tests involving FluentFTP.GnuTLS were failing.
1.0.5 -> 1.0.20 and also lib version 3.7.8 -> 3.8.0
** This is the corrected commit / merge. The previous one was incorrect and was reverted. **

FluentFTP nuget updates needed to run our integration tests (corrected)

---

FluentFTP.Tests/Integration/Tests/ConnectTests.cs
FluentFTP/Client/AsyncClient/AutoConnect.cs
FluentFTP/Client/AsyncClient/AutoDetect.cs
FluentFTP/Client/Config/AutoDetect.cs
FluentFTP/Client/Interfaces/IAsyncFtpClient.cs
FluentFTP/Client/Interfaces/IFtpClient.cs
FluentFTP/Client/Modules/ConnectModule.cs
FluentFTP/Client/SyncClient/AutoConnect.cs
FluentFTP/Client/SyncClient/AutoDetect.cs

Waiting for your comments / changes / ideas
Config Object location (for now, first idea of mine):
The config object looks like this:
```cs
using System.Collections.Generic;
using SysSslProtocols = System.Security.Authentication.SslProtocols;
namespace FluentFTP {
public class FtpAutoDetectConfig {
/// <summary>
/// Use a new cloned FtpClient for testing connection profiles (true) or use the source FtpClient (false)
/// </summary>
public bool CloneConnection { get; set; } = true;
/// <summary>
/// Find all successful profiles (false) or stop after finding the first successful profile (true)
/// </summary>
public bool FirstOnly { get; set; } = true;
/// <summary>
/// Also try the very seldom used Implicit mode
/// Default is try implicit, otherwise many would need a code change
/// as per …
```

Model Auto Detect with config object, first draft, works fine.

---

FluentFTP.Tests/Unit/ParserTests.cs

Someday somebody will fix this generically or remove the entries that don't have a year. No time right now, testing some other stuff

Fix ParserTests.cs unix date problem

---

FluentFTP/Client/AsyncClient/AutoDetect.cs
FluentFTP/Client/BaseClient/Logger.cs
FluentFTP/Client/SyncClient/AutoDetect.cs
FluentFTP/Helpers/Collections.cs
FluentFTP/Model/Functions/FtpAutoDetectConfig.cs

This is my take on how to do this.
So there is no need to put the 
```cs
public object[] ToArray() {
return new object[] {
"CloneConnection="+CloneConnection,
"FirstOnly="+FirstOnly,
"IncludeImplicit="+IncludeImplicit,
"RequireEncryption="+RequireEncryption,
"ProtocolPriority="+ProtocolPriority,
};
```
array as duplicate typing into the config file.
The output is generated automagically (here is an example):
```txt
>         AutoDetect(CloneConnection=true, FirstOnly=false, IncludeImplicit=true, RequireEncryption=false, ProtocolPriority=Tls11 Tls12, ProtocolPriority=Default)
>         AutoConnect()
>         AutoDetect(CloneConnection=false, FirstOnly=true, IncludeImplicit=true, RequireEncryption=false, ProtocolPriority=Tls11 Tls12, ProtocolPriority=Default)
Status:   Auto-Detect trying …
```

Auto-print config file properties

---

FluentFTP/Client/BaseClient/Logger.cs

When logging is disabled we still do a lot of work only not to log it.
This PR introduces `AnyLoggingIsEnabled()` to avoid this work if no kind of logging is enabled.

Avoid creating strings when logging is disabled

---

FluentFTP/Client/AsyncClient/DownloadUriBytes.cs
FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/Interfaces/IAsyncFtpClient.cs
FluentFTP/Client/Interfaces/IFtpClient.cs
FluentFTP/Client/SyncClient/DownloadUriBytes.cs

After a rather strange discourse on issue #1320, from which one small idea stands out:
"It would be nice to have a (more or less) one-liner replacement for ...GetBytes(ftp_uri) as seen in .NET with HttpClient".
Apart from the fact that Microsoft is neglecting, deprecating or dropping most of its interfaces to ftp, this approach is not as flexible as having full control over the way an ftp server is accessed.
Nonetheless, here is a quick way to get something from an ftp url and let's add it to the API (the code to do this is simple, I wonder what the TO was ranting about):
**`DownloadUriBytes(...)`**
Sample code shows up the functionality and ease of use:
```cs
using (var client = new FtpClient()) {
// Add config statements as needed, for example:
client.Config.ValidateAnyCertificate = …
```

Add new API function "DownloadUriBytes"

---

FluentFTP/Client/AsyncClient/GetObjectInfo.cs
FluentFTP/Client/SyncClient/GetObjectInfo.cs

When MLSD is not supported, GetListing is used.
That's fine, but even if this is successfull, a warning message is issued anyway, saying that the GetLising failed.
Helpful for (but not a fix for) issue #1324

Get object info

---

FluentFTP/Client/AsyncClient/Authenticate.cs
FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/AsyncClient/OpenRead.cs
FluentFTP/Client/AsyncClient/OpenWrite.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/BaseClient/ReadStaleData.cs
FluentFTP/Client/SyncClient/Authenticate.cs
FluentFTP/Client/SyncClient/OpenRead.cs
FluentFTP/Client/SyncClient/OpenWrite.cs
FluentFTP/Model/FtpClientState.cs
FluentFTP/Model/FtpConfig.cs

This will alleviate problems caused by users **still** using the obsolete OpenRead API function.
In the beginning, OpenRead would leave stale data (its success or failure response) on the socket. Users would typically just leave it there, or some might pick it up with a `GetReply(...)`.
Then, someone decided to handle stale data which occasionaly caused commands and replys to go out of sync, and decided to reconnect. Which didn't work initially anyway.
As things got fixed, stale data was handled more and more strictly, thus OpenRead was now causing real problems.
This fix alleviates this, but it does not recognize any failures.

Ignore stale data after OpenRead/OpenWrite

---

FluentFTP/Client/BaseClient/ReadStaleData.cs

On fast servers, stale data arrives long before anyone would expect it

Handle stale data that arrives very quickly

---

FluentFTP/Client/AsyncClient/GetReply.cs
FluentFTP/Client/BaseClient/GetReply.cs

As a final final touch, if a user executes `GetReply(...)` himself after using `OpenRead(...)`, we can turn off the boolen `Status.IgnoreStaleData`, as a reply will not be forthcoming.

GetReply, if used after OpenRead, should turn off ignoreStaleData

---

FluentFTP/Client/SyncClient/GetNameListing.cs

"Some FTP servers throw 550 for empty folders. Absorb these..."
Well, now here is one that issues "450".
Added to the IF statement.

Fix #1358 Bug 2... NLST reports 450 on empty folder

---

FluentFTP/Client/Modules/ConnectModule.cs
FluentFTP/Model/Functions/FtpAutoDetectConfig.cs

I added an option to treat timeouts during the autodetection as a failed detection attempt, instead of aborting with an exception.
- I added a boolean property `AbortOnTimeout` to the `FtpAutoDetectConfig` which is `true` by default.
- I adjusted the `ConnectModule` to honor the flag and treat TimeoutExceptions accordingly.
I use FluentFTP in a .NET 4.6.2 project and I had an issue connecting to a FileZilla server with FTPS enabled.
While my code works in .NET 5 and higher, I get a Timeout error with 4.6.2.
Investigating this, I determined that the Socket internally is getting the error 997 (IO PENDING), which should not necessarily be an aborting error, but is not handled my the .NET Framework. 
FluentFTP is throwing a `TimeoutException` whenever the Socket is not connected after calling …

Timeouts during auto detection

---

FluentFTP/Client/SyncClient/FileExists.cs

Finally managed to debug why in case there **is no server handler** assigned or detected, `FileExists(...)` will ignore the SIZE FEAT and use NLST instead.

Fix for 1371, 1358

---

FluentFTP.Tests/Unit/HelperTests.cs
FluentFTP/Client/Modules/ConnectModule.cs

47.1.0 introduced a "Config" object for AutoDetect(...).
This uses a static list, which is then modified by the config options.
In a multi-threaded environment (multiple AutoDetects running at the same time), such a construct is not thread safe.
Fixes: #1384
Basically, create a working copy of the static list in the static method which is then used internally after it is modified.
Mark the static list as readonly
Fix a small logic error for IncludeImplicit
Update helper tests to run cleanly on current config object
Checked integration tests

AutoDetect GetWorkingProfileFromHost not thread safe

---

FluentFTP/Streams/FtpSocketStream.cs

Appears to be a typo. Updating the directive to "NET5_0_OR_GREATER", matching other examples in the same file also "unhides" the code as expected in visual studio.

Update FtpSocketStream.cs to fix apparent typo "#if NET50_OR_LATER" to "#if NET5_0_OR_GREATER"

---

FluentFTP/FluentFTP.csproj

NET50_OR_LATER is no longer needed as a symbol: Any conditional compilation using these symbols has been removed from the code.

Remove ***_OR_LATER

---

FluentFTP.CSharpExamples/CSharpExamples.csproj
FluentFTP.VBExamples/VBExamples.vbproj
FluentFTP/FluentFTP.csproj

NET50 and NET60 not used in code
TFM net60 -> net6.0 and net50 -> net5.0 (adhere to MS standard)

NET50 and NET60 not used in code and TFM moniker correction net60 -> net6.0 and net50 -> net5.0

---

FluentFTP.Logging/FluentFTP.Logging.csproj
FluentFTP.Tests/FluentFTP.Tests.csproj
FluentFTP.Xunit/FluentFTP.Xunit.csproj

We were a little "behind" in some cases. These work.
The packages used in the test suite cannot be updated without some small changes to the source - keeping those on the bavk burner for a rainy day.

Update some selected NuGet packages

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/IsStillConnected.cs
FluentFTP/Client/AsyncClient/Noop.cs
FluentFTP/Client/AsyncClient/TransferFile.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/IsStillConnected.cs
FluentFTP/Client/SyncClient/Noop.cs
FluentFTP/Client/SyncClient/TransferFile.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs

Gave Noop() a parm to avoid needing to manipulate NoopInterval. This made it necessary to touch all users of Noop (there are not many).
This concludes the effort to detect connection status.

Clean up IsStillConnected(), Noop() et.al.

---

FluentFTP/Client/AsyncFtpClient.cs
FluentFTP/Client/BaseFtpClient.cs
FluentFTP/Client/FtpClient.cs
FluentFTP/Client/Interfaces/IInternalFtpClient.cs

I finally found this while debugging something else.
It effectively prevented ASYNC connection handling to take place.

Fix long standing SYNC/ASYNC method interface mixup

---

FluentFTP/Client/AsyncClient/DisableUTF8.cs
FluentFTP/Client/Interfaces/IAsyncFtpClient.cs
FluentFTP/Client/SyncClient/DisableUTF8.cs

The async version of DisableUTF8, which invokes Execute(....) NEEDS to be coded for async operation which was not the case.

Fix "DisableUTF8()" sync and async(bug)

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/BaseClient/Connect.cs
FluentFTP/Client/BaseClient/Disconnect.cs
FluentFTP/Client/BaseFtpClient.cs
FluentFTP/Client/Interfaces/IBaseFtpClient.cs

Final clean up for the BaseClient Connect() / Disconnect() legacy
Move Connect() and Disconnect() statements to their own (albeit) small .cs files in the BaseClient folder.

Move BaseClient Connect / Disconnect to .cs files

---

FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/BaseClient/Daemon.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/BaseClient/GetReply.cs

1.	Windows GUI environment using FTP client
2.	Typo in Daemon.cs
3.	In some cases Execute.cs will invoke another Execute.cs via GetWorkingDIrectory.cs - produces deadlock
4.	Typo in Getreply.cs

Change semaphore logic to prevent deadlocks

---

FluentFTP/Client/BaseClient/Daemon.cs

The NOOP daemon was too hesitant in some cases where dropped connections produce horrendous exceptions. Simply ignoring these was not the right tactic. When the daemon discovers the problem, it is not enough to stop the timer loop - no, it is necessary to shut down the control connection instead of leaving it in a strange state.

Give NOOP daemon more power

---

FluentFTP/Client/AsyncClient/Noop.cs
FluentFTP/Client/BaseClient/Noop.cs

After gaining the Semaphore - check if the connection is still viable, avoid sending a NOOP into the TCP void...

Improve Noop API handling of disconnections

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs

fixes the exit on stopPosition scenario in DownloadFileInternalAsync method
not sure if this is the right fix, as i had to set earlySuccess = true; otherwise i would get 550 error

#1444 break download loop if stopPosition reached

---

FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/Modules/ConnectModule.cs
FluentFTP/Client/Modules/ServerStringModule.cs

It is senseless to reconnect on SslSessionLength reached for a QUIT and for a NOOP command it is better to defer.

Exclude some commands from reconnect

---

FluentFTP/Client/AsyncClient/DownloadFile.cs
FluentFTP/Client/SyncClient/DownloadFile.cs

Fixed issue in: #1452
In this PR I updated the progress updating of downloading files both in Sync Client and Async Client. 
I did not update the Upload Files, since I think that updating progress in there will be the same, and when you download files, there is a case where you have some files and you simply want to skip them. 
Problem of current progress is that, when you are downloading, it did not showed progress on "skipped" file, it just ignore it, and didn't fire any progress update.  
Now with this PR, it increases the count of files checked / need to download. 
Reason behind of this modification was, that when you want to show download progress to user, user can think that program doesn't do anything, when on background it does things. It is just a nice little thing to keep user …

Updated the Progress of downloading files.

---

FluentFTP/Client/BaseClient/CloseDataStream.cs
FluentFTP/Client/Interfaces/IInternalFtpClient.cs
FluentFTP/Streams/FtpDataStream.cs

Using the same technique as in https://github.com/robinrodricks/FluentFTP/issues/1461, I have fixed issue #1460.
Note: At some point in time, Close, Dispose and other cleanups need to be re-examined as to how well they are "fitted to async". There might still be some async operations happening somewhere that inadvertently invoke sync methods.
Note that even if a client is not *cloned*, a sync datastream close was being invoked, because as the OP mentioned, there was **no async** datastream close **ever present**.

This is a bugfix for #1460

---

FluentFTP/Streams/FtpDataStream.cs

This is in preparation for a upcoming PR to handle async closing of FtpData... and SocketDataStreams

Refactor FtpDataStream Close(sync) to return void

---

FluentFTP/Client/AsyncFtpClient.cs

Now that there is a DisposeAsync unconditionally available, no need for the #if

AsyncFtpClient: This is no longer "TODO".

---

FluentFTP/Client/AsyncClient/Disconnect.cs
FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/AsyncClient/ExecuteDownloadText.cs
FluentFTP/Client/AsyncClient/GetListing.cs
FluentFTP/Client/AsyncClient/GetNameListing.cs
FluentFTP/Client/AsyncClient/OpenActiveDataStream.cs
FluentFTP/Client/AsyncClient/OpenPassiveDataStream.cs

Finally, make the AsyncFtpClient use the CloseAsync pattern instead of Close(sync) in all places where this occurred.

AsyncFtpClient: Modify all "Close()" usage to "await CloseAsync()"

---

FluentFTP/Streams/FtpSocketStream.cs

Dispose and DisposeAsync call flush internally and execute additional cleanup logic.

Call Dispose/DisposeAsync on BufferedStream instead of Flush/FlushAsync

---

FluentFTP/Streams/FtpDataStream.cs

This inadvertent change from "new" to "override" in a previous commit makes DownloadFileInternal and UploadFileInternal fail on SYNC clients. So quickly quickly change this back to "new" instead of "override".

"new" attribute absolutely needed on FtpDataStream.Close

---

FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs

Although in SYNC (as opposed to ASYNC) this would seem redundant, it makes the SYNC code and the ASYNC code track each other more.

Clarify the call destination, similar to code in ASYNC

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs

If `GetFileSize` fails to determine the size `fileLen` will be -1 here. In that case we would end up with a negative amount of bytes to write.

fileLen may be negative

---

FluentFTP/Streams/FtpSocketStream.cs

The recent changes to ASYNC and also cleanup of SYNC dispose had inadvertently taken the FtpSslStream "graceful" TLS termination code out of the sequence, effectively disabling it. These two "Close" statements bring this (hard earned) functionality back.
Note that the ASYNC flavor of this close is not totally block free.
FtpSslStream needs a slight recode to also honor the Async disposing paradigms introduced recently. TBD

Restore call to FtpSslStream graceful TLS termination

---

FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs

Previously, log messages for Uploaded/Downloaded bytes were in this form:
**Status:   Downloaded 1073741824 bytes**
Now, they are:
**Status:   Downloaded 1073741824 bytes (9,212s, 111,2 MB/s)**
This was useful when checking the effect of turning on/off buffering.

Enhance log message Uploaded/Downloaded bytes

---

FluentFTP/Streams/FtpSocketStream.cs

No need to laboriously determine correct local time for this functionality (including Daylight Saving Time etc.).

UtcNow instead of Now : much less overhead

---

FluentFTP.CSharpExamples/CustomParser.cs
FluentFTP/Client/AsyncClient/OpenFXPConnection.cs
FluentFTP/Client/BaseClient/GetPassivePort.cs
FluentFTP/Client/Modules/LogMaskModule.cs
FluentFTP/Client/SyncClient/OpenFXPConnection.cs
FluentFTP/Helpers/Hashing/HashParser.cs
FluentFTP/Helpers/Parsers/MachineListParser.cs
FluentFTP/Servers/Handlers/OpenVmsServer.cs

`new Regex()` doesn't cache the build, but `Regex.Match()` does
[`\d` matches much more than `[0-9]`](https://learn.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#decimal-digit-character-d)

Utilize caching Regex calls

---

FluentFTP.Tests/Integration/Tests/FileTransferTests.cs
FluentFTP/Streams/FtpDataStream.cs
FluentFTP/Streams/FtpSocketStream.cs

Available in NETSTANDARD2_1 and NET5_0_OR_GREATER, the base class functions in Stream for backwards compatibility rent an array and copy the span to it and then call the old array based functions.
As an optimization FtpDataStream and FtpSocketStream can override these functions and pass the call directly onto the wrapped stream.
Closes #1570

Override Read(Span), ReadAsync(Memory), Write(ROS), WriteAsync(ROM) in streams

---

FluentFTP.Tests/Unit/DateTimesTests.cs
FluentFTP/Helpers/DateTimes.cs

DateTimes.ParseFtpDate accepts the 'format' argument, which was not used during the date time parsing. Additionally, DateTimes unit tests are added.

DateTimes.ParseFtpDate consider 'formats' when parsing DateTime.

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/AsyncClient/Noop.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/BaseClient/GetReply.cs
FluentFTP/Client/BaseClient/Noop.cs
FluentFTP/Client/BaseClient/NoopDaemon.cs
FluentFTP/Client/BaseClient/Properties.cs
FluentFTP/Client/SyncClient/Connect.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs
FluentFTP/Model/FtpClientState.cs
FluentFTP/Model/FtpConfig.cs
FluentFTP/Proxy/SyncProxy/FtpClientHttp11Proxy.cs
FluentFTP/Streams/FtpSocketStream.cs

The current implementation of Socket.Poll inline in "IsConnected", which is a property of socketstream needs to be isolated from the getter. Firstly, it is not guaranteed to be invoked regularly, secondly it needs an async implementation as well as a sync one. And the list of problems gets even longer when trying to implement when a poll is allowed to occur and when not. See #1582.
So, in order for clean socket polling if the user desires it, a second daemon is to be implemented, to be called "PollDaemon".
The current "Daemon" shall forthwith be called "NoopDaemon", otherwise unchanged apart from renaming.

Rename Daemon->NoopDaemon in preparation for "PollDaemon" coming soon

---

FluentFTP/Client/AsyncClient/Disconnect.cs
FluentFTP/Client/SyncClient/Disconnect.cs

I found this when testing with multiple connects for a single client.

Fix Disconnect bug

---

FluentFTP/Client/BaseClient/GetReply.cs

In edge cases, the Noop "tickle" commands should also be detected in the Noop timing.

Improve Noop handling

---

FluentFTP/Streams/FtpSocketStream.cs

If you wanted to cancel a read operation, a non-catchable exception always flew here. This could not be handled due to the fact that it was registered on the cancellation token. 
The ReadTimeout still works, as the Read method throws an exception as soon as the cts expires.
In the new setup, the connection is still closed and an exception is now thrown correctly.

Fixed uncatchable Exception after cancellation of read in FTPSocketStream

---

FluentFTP/Client/BaseClient/Properties.cs
FluentFTP/Client/Interfaces/IBaseFtpClient.cs
FluentFTP/Streams/FtpSocketStream.cs

This was well meant, but it conflicts with .NET definitions. See also #1623. And: It is not even used.

Remove unused code

---

FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/AsyncClient/Disconnect.cs
FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/AsyncClient/UploadFileInternal.cs
FluentFTP/Client/AsyncFtpClient.cs
FluentFTP/Client/BaseClient/CloseDataStream.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/BaseClient/GetReply.cs
FluentFTP/Client/BaseClient/NoopDaemon.cs
FluentFTP/Client/BaseClient/Properties.cs
FluentFTP/Client/BaseFtpClient.cs
FluentFTP/Client/Modules/ConnectModule.cs
FluentFTP/Client/SyncClient/Connect.cs
FluentFTP/Client/SyncClient/Disconnect.cs
FluentFTP/Client/SyncClient/DownloadFileInternal.cs
FluentFTP/Client/SyncClient/UploadFileInternal.cs
FluentFTP/Enums/FtpRealConnectionsStates.cs
FluentFTP/Model/FtpClientState.cs
FluentFTP/Model/FtpConfig.cs
FluentFTP/Streams/FtpDataStream.cs
FluentFTP/Streams/FtpSocketStream.cs

**Use** Task.Factory.StartNew
**Use** CancellationToken
**Improve** code and use intermediate connection state to indicate lost connection
**Improve** IsConnected - handle sync **and async** close situations, remove extranseous socket.Poll calls, use intermediate connections state to decide return valie
**Improve** Close/Dispose logic further - add detailed logging of Close/Dispose failures for future debugging in possible user logs when issues are reported
**Allow connection failure status tracking** with the help of NoopDaemon before IsConnected decides true/false based on socket state only.

Remove socketPoll, improve Daemon, fix/maintain code

---

FluentFTP/Client/AsyncFtpClient.cs

Replace `DisposeAsync().ConfigureAwait(false).GetAwaiter().GetResult();`
by `Task.Run(async () => await DisposeAsync()).Wait();`.
In a GUI environment the preferred way to invoke an async routine from a sync method is prone to deadlocks.
This way is safer.

Issue Fix #1634

---

FluentFTP.Tests/Unit/ParserTests.cs
FluentFTP/Client/AsyncClient/Connect.cs
FluentFTP/Client/AsyncClient/GetObjectInfo.cs
FluentFTP/Client/BaseClient/Listing.cs
FluentFTP/Client/Modules/ServerFeatureModule.cs
FluentFTP/Client/Modules/ServerStringModule.cs
FluentFTP/Client/SyncClient/Connect.cs
FluentFTP/Client/SyncClient/GetObjectInfo.cs
FluentFTP/Enums/FtpCapability.cs
FluentFTP/Enums/FtpListOption.cs
FluentFTP/Helpers/FtpListParser.cs

See #1635 
The capability should be called MLST in the code and not MLSD. Global rename needed.

Rename FEAT capability MLSD -> MLST

---

FluentFTP/Helpers/Hashing/HashAlgorithms.cs
FluentFTP/Streams/FtpSocketStream.cs

I was investigating a race condition in my app. I haven't found the root cause yet, but this part took my attention in FluentFTP's code when browsing through the stack:
- The `ContainsKey` + retrieve pairs are redundant when a single `TryGetValue` would work. 
- A dictionary `.Add` would throw `ArgumentException` for duplicate keys, but `cache[host] = value` wouldn't.
I know that there is no reason for those pieces of code to fail for a single-threaded type, but still it's marginally faster, and more fault tolerant :)

Improve dictionary lookups

---

FluentFTP.Tests/Integration/Tests/FileTransferTests.cs

This missing `GetReply()` causes stale data prior to the `OpenRead(...)`. Fortunately, this doesn't cause a failure in the test, but for cosmetic reasons, adding the `GetReply()` as stated in the Documentation is a good thing.

Fix incorrect call sequence (Obsolete OpenWrite/OpenRead)

---

FluentFTP/Streams/FtpSslStream.cs

Just to clarify why this close notify hack is only needed in some versions of .NET, in case the comment at the top of the file is not noticed.

add comment

---

FluentFTP/Client/BaseClient/GetReply.cs
FluentFTP/Client/BaseClient/ReadStaleData.cs

Use `Task.Delay` instead of `Thread.Sleep` in async methods.
Introduced in:
* https://github.com/robinrodricks/FluentFTP/commit/372ff88771023fe23fab65505594f17f0acc5f4e#diff-3d3d07d656110497cd0b89ccd49f2a2614e7296bfe0da620839ac6d0efae67beR110
* https://github.com/robinrodricks/FluentFTP/commit/dc511d8c2e46d986f4bf9d4ab26252650f45128f#diff-1295cd645e59fea47aeb890b57fab668a6945bd4442997e264f4e6f297015908R114

Use `Task.Delay` instead of `Thread.Sleep`

---

FluentFTP/Client/AsyncClient/FileExists.cs
FluentFTP/Client/SyncClient/FileExists.cs

For the changed C# expressions, let:
* `a` be `HasFeature(FtpCapability.SIZE)`, 
* `b` be `ServerHandler == null` and
* `c` be `ServerHandler.DontUseSizeEvenIfCapable(path)`.
On mathematical form, the expressions are now `a && (b || !b && c)`.
As proven by [Wolfram Alpha](https://www.wolframalpha.com/input?i=%28a+%26%26+%28b+%7C%7C+%21b+%26%26+c%29%29+%3D+%28a+%26%26+%28b+%7C%7C+c%29%29) this is equal to writing `a && (b || c)`
Translating back to C# it means we can omit the `ServerHandler != null` checks.

Remove redundant null checks

---

FluentFTP/Streams/FtpSocketStream.cs

If the delegate throws an exception this is not properly caught. 
This change aligns with #1613
Caught by [CS4014](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014)
This fixes #1742

Do not call CancellationToken.Register with async delegate

---

FluentFTP.Tests/Unit/ParserTests.cs
FluentFTP/Client/AsyncClient/Execute.cs
FluentFTP/Client/BaseClient/Execute.cs
FluentFTP/Client/BaseClient/GetReply.cs
FluentFTP/Client/Interfaces/IAsyncFtpClient.cs
FluentFTP/Client/Interfaces/IFtpClient.cs
FluentFTP/Client/Interfaces/IInternalFtpClient.cs
FluentFTP/Client/SyncClient/Execute.cs

Sorry to bring this dogshit of #1746 up again, but after a while of testing I discovered that the previous approach wasn't quite good enough after all. We also have scenarios where we have a valid positive response, but the error case of the same command brings up an ill-formed response. In addition, there are multiline success responses while the error response is single-line, well, all of the possible ill-formed responses are single-liners (as far as I can tell currently).
As a result, I figured to change this `linesExpected` approach a bit to better fit these requirements. Feel free to have a look, I'd be also open to keep the special case code in my own library, in which case it would be fine to make the `GetReply` method(s) virtual so that I can inherit a subclass, overwriting the …

Rework accepting custom responses (#1746)

---

FluentFTP/Monitors/AsyncFtpMonitor.cs
FluentFTP/Monitors/BaseFtpMonitor.cs
FluentFTP/Monitors/BlockingAsyncFtpMonitor.cs

BaseFtpMonitor:
- Set properties internal access modifier to protected, so derived classes can reach them
- Set StartTimer and StopTimer functions access modifier to protected, so derived classes can call them
- Set GetListingOptions and HandleUnstableFiles functions access modifier to protected virtual, so derived classes can override them
AsyncFtpMonitor:
- Set PollFolder and GetCurrentListing functions access modifier to protected virtual, so derived classes can override them
BlockingAsyncFtpMonitor:
- Set Start function access modifier to public virtual, so derived classes can override it
- Set PollFolder and GetCurrentListing functions access modifier to protected virtual, so derived classes can override them

Rework FtpMonitor class's access modifiers
