robinrodricks/FluentFTP

- FluentFTP/FtpClient.cs
- FluentFTP/Proxy/FtpClientHttp11Proxy.cs
- FluentFTP/Proxy/FtpClientProxy.cs
Processed the Diff file from Zoltan666 to an Pull Request
> Fixes for Proxy

- FluentFTP/FtpClient.cs
- FluentFTP/Proxy/FtpClientHttp11Proxy.cs
- FluentFTP/Proxy/FtpClientProxy.cs
- FluentFTP/Proxy/FtpClientUserAtHostProxy.cs
The incorrect client type was being created for the proxy clients.
The proxy responses weren't being processed and were getting mixed in
with the regular FTP conversation.
> Fix more proxy bugs.

- README.md
Fixed some small typos in the README.md file
> Typos in example inside README

- FluentFTP.Tests/Tests.cs
Added Test Cases as requested in response to pull request #79
> Added Test Cases As Requested For Async Methods

- FluentFTP.Examples/Debug.cs
- FluentFTP/FtpClient.cs
- FluentFTP/FtpTrace.cs
- README.md
- Fixed FtpTrace bug
- Updated Documentation about FtpTrace & FtpVerify
- Fixed ordering of events in upload to improve reliability upon a verification failure
> Fixed FtpTrace Bug & Fixed Ordering in Uploads

- FluentFTP/Client/FtpClient_Listing.cs
- FluentFTP/Helpers/FtpListParser.cs
Add a listing fix for on the AS400, and make the listing methods automatically 'retry' if it turns out we picked the wrong date format.
> Misc. listing fixes

- FluentFTP/Client/FtpClient_LowLevel.cs
- FluentFTP/Client/FtpClient_Management.cs
This fixes some FTP servers that don't work correctly unless you do a SIZE in binary...
Possible fix for #137
> Temporarily switch into BINARY mode before running 'SIZE' command.

- FluentFTP/Client/FtpClient_Management.cs
- FluentFTP/IFtpClient.cs
Simply, just a Interface so we can write Unit Tests for our projects.
> Added a Interface for the FtpClient

- FluentFTP/FluentFTP.csproj
> Include the IFtpClient interface in FluentFTP.csproj

- FluentFTP/Client/FtpClient_HighLevel.cs
> Revert "Removed the fixes from high-level functions which read the final reply"

- FluentFTP/Stream/FtpDataStream.cs
- FluentFTP/Stream/FtpSocketStream.cs
> Revert "Dispose of FtpDataStream Now Reads Control Reply"

- FluentFTP.Tests/Tests.cs
- FluentFTP.Tests/Tests.csproj
- FluentFTP.Tests/XUnitShim.cs
- FluentFTP.Tests/xunit.runner.json
- FluentFTP/Client/FtpClient_Hash.cs
- FluentFTP/Client/FtpClient_HighLevel.cs
- FluentFTP/Client/FtpClient_Listing.cs
- FluentFTP/Stream/FtpDataStream.cs
- FluentFTP/Stream/FtpSocketStream.cs
- appveyor.yml
Following on from my previous suggestion re: automated builds, I decided to split this into two stages:
1. Implement Continuous Integration using AppVeyor (Free for open source projects)
2. Add unit testing with a live server
Since we don't have a live server that we can test against, I thought it would be good to start with at least the first stage. (while I'm looking into converting the Tests project into a working xUnit proj)
The main benefit is that each commit will have a build run against it, so you can immediately see whether there are compilation errors. Better yet, it will also be displayed on the PR screens, to make sure that pull requests won't bring in any compilation errors :)
To get this working, the only thing you need to do is create an AppVeyor account and point it to …
> Basic CI using AppVeyor

- FluentFTP/Client/FtpClient_Connection.cs
- FluentFTP/Client/FtpClient_LowLevel.cs
Fix DownloadFileInternal not recognizing the download data type
with EnableThreadSafeConnections enabled.
Resolves #184
> Fix download file data type bug.

- FluentFTP/Client/IFtpClient.cs
This pull request will add the async methods to IFtpClient.
This will fix #278
> Fixes #278 Added async versions of methods to IFtpClient

- FluentFTP/Client/IFtpClient.cs
I figured out that I needed more methods. So now I have included all async methods in the IFtpClient.
> Added more async versions of methods to IFtpClient

- FluentFTP/Proxy/FtpClientHttp11Proxy.cs
- FluentFTP/Proxy/FtpClientProxy.cs
> Implement async codepath for Http Proxy

- FluentFTP/Client/FtpClient_Connection.cs
Helps to solve some of NLST problems for Xlight FTP Server. Lets to work SIZE or  MDTM in FileExists().
> Add "can't find file" string to fileNotFoundStrings. 

- FluentFTP/Stream/FtpSocketStream.cs
This reduces the large number of small marshalled writes to the NetworkStream, massively increasing performance when using SSL.
During testing of these changes a file which was previously taking 1 minute 5 seconds to upload is now taking 12 seconds to upload.
Closes #354
> Added BufferedStream between SslStream and NetworkStream

- FluentFTP/Client/FtpClient_HighLevel.cs
- FluentFTP/Client/FtpClient_LowLevel.cs
- FluentFTP/Client/FtpClient_Management.cs
Context:
- https://stackoverflow.com/a/18335900/1062614
- https://stackoverflow.com/a/37052176/1062614
> Fixed issue with infinite loop, plus other improvements

- FluentFTP/Client/FtpClient_HighLevel.cs
Fixes a missing bracket that breaks the build
> Fix missing bracket

- FluentFTP/Client/FtpClient_HighLevel.cs
- FluentFTP/Client/IFtpClient.cs
- FluentFTP/Helpers/FtpProgress.cs
Hi,
i thought it would be nice if we can access transfer speed and the eta for transfer via high level api.
I am not sure if all variable names are okay and also if it my way to calculate the transfer speed is best / cleanest way.
apart from this all changes regarding download (i didn't test upload yet) working fine.
> Expose download speed and eta for a transfer to high level api

- FluentFTP/Client/FtpClient_LowLevel.cs
- FluentFTP/Stream/FtpSocketStream.cs
> .net core hangs

- FluentFTP/Client/FtpClient_LowLevel.cs
We had a problem with ftp_srv.
For more info visit: https://github.com/robinrodricks/FluentFTP/issues/379
> Fix async mode in active connection with crypting

- FluentFTP/Client/FtpClient_Connection.cs
- FluentFTP/Client/FtpClient_Properties.cs
added a variable in the properties and a command in both Connect and ConnectAsync if the value is set to true
> Added support for the HOST command to be sent after the handshake

- FluentFTP/Extensions/HashAlgorithm/CRC32.cs
- FluentFTP/Helpers/FtpHash.cs
- FluentFTP/Helpers/FtpHashAlgorithms.cs
Hi,
i added CRC32 support cause most of the FTP servers i use only supports this.
To be honest i didn't create the crc32 class by myself. I used [this ](https://github.com/bentonstark/starksoft-aspen/blob/master/Starksoft.Aspen/Crc32.cs ) as base. I hope this not a problem (due license or someting else) and you can accept this pull request.
- n0ix
> Added XCRC (aka CRC32) support

- FluentFTP/Rules/FtpFIleNameRegexRule.cs
- FluentFTP/Rules/FtpFolderNameRegexRule.cs
- FluentFTP/Rules/FtpRegexRule.cs
- FluentFTP/Utils/FtpExtensions.cs
I added a simply FtpRule which can check if any of the supplied RegEx pattern matches.
I thought that may be usefull.
> New FtpRule => FtpRegexRule

- FluentFTP/Client/FtpClient_FolderUpload.cs
Fix Replace of LocalFolder with '/' Prefix on Windows.
> FIX: #559 Issue replacing path during UploadDirectory

- FluentFTP/Client/FtpClient_FileDownload.cs
- FluentFTP/Client/FtpClient_FileUpload.cs
- FluentFTP/Utils/FtpExtensions.cs
After update from version 23.1.0 to 32.2.1 I have started getting errors like [this](https://github.com/robinrodricks/FluentFTP/issues/410) from `FtpClient.UploadAsync` method.
So, maybe it will be correct to resume upload after receiving _unexpectedEOF_ error.
> ResumeUpload: Resume when unexpectedEOF error received while uploading

- FluentFTP/Client/FtpClient_FileDownload.cs
- FluentFTP/Client/FtpClient_FileUpload.cs
> Issue #577

- FluentFTP/Helpers/FtpListParser.cs
> Clear custom parser when removing parser or clearing all parsers

- FluentFTP/Client/FtpClient_FileVerification.cs
> #626 UploadDirectory fails for some files "Unable to read data from the transport connection

- FluentFTP/Client/FtpClient_FileUpload.cs
While resuming a FTP transfer, we can't rely on our knowledge of the actual offset really written on the remote server.
Thus I inverted the logic, when opening a new connection for resume (in ResumeUpload) we retrieve the actual remote offset, so we can reposition our local stream to the effective position.
this fixes for me issue #283
> Fix Resume when the connection drops

- FluentFTP/Client/IFtpClient.cs
Does what it says on the tin. FtpClient.Download has a default value, IFtpClient.Download does not
> Set default value for restartPosition in Download method on IFtpClient to match FtpClient method

- FluentFTP/Client/FtpClient_Connection.cs
This fixes the problem of URI ports not being respected (#652). The Host field will now be set to the Uri Host.
> WIP: Issue 652

- FluentFTP/Client/FtpClient_Stream.cs
Debugging the following log message:
"Command: EPSV
Response: 227 Entering Passive Mode( **, **, **, **, 143,225).
"
Which resulted in an exception "Failed to get the ESPV port from ..."
Determined that the regex being used by GetEnhancedPassivePort was not working with that response. Which is no surprise, as the response is not a Enhanced(Expanded) passive response. Unsure why the FTP server responds this way, but having the function use GetPassivePort in this case results in the response port being parsed.
> added fallback to regular passive if the response is not Extended

- FluentFTP.CSharpExamples/LocalIpAddress.cs
- FluentFTP/Client/FtpClient_Connection.cs
- FluentFTP/Client/FtpClient_Properties.cs
- FluentFTP/Helpers/LocalPorts.cs
- FluentFTP/Streams/FtpDataStream.cs
- FluentFTP/Streams/FtpSocketStream.cs
As promised in discussion in https://github.com/robinrodricks/FluentFTP/issues/713 
A PR with only *.cs files
Not sure it will build with all targets (net20 and such, who still uses that anyway ?)
> Locally bind to specific address via new LocalIpAddress property

- FluentFTP/Client/FtpClient_FileUpload.cs
New chunk's position and offset reset.
Stream length sum with chunk size and uploaded file size.
> append method was not appending.

- README.md
System/i runs (among others) OS/400.
System/z runs (among others) z/OS
> Small tweak in REAMDE.md for IBM servers System/z and System/i

- FluentFTP/Client/FtpClient_FileProperties.cs
This seemed like a good idea after all. Saves a lot of coding in the user code.
> GetzOSFileSize(string path) API function

- FluentFTP/Client/FtpClient_Properties.cs
- FluentFTP/Helpers/Parsers/FtpIBMzOSParser.cs
This was one of your suggestions
> Enhance the z/OS listing parser to get LRECL (via XDSS) on behalf of user and new Wiki text

- FluentFTP/Client/FtpClient_Connection.cs
See the new wiki text in PR #788
> SITE DATASETMODE and QUOTESOVERRIDE commands on connect to IBM z/OS FTP server

- FluentFTP/Client/FtpClient_Connection.cs
Small tweak. No executes without an error check.
> Error check on z/OS init commands

- FluentFTP/Client/FtpClient_FileManagement.cs
Although it does not hurt and causes no error, it is unclean to have SIZE and MDTM commands being issued to z/OS, even if that server reports these as being available.
Since a path like `TEST.TST` (Note: no leading slash) could be **EITHER** a z/OS dataset **OR** a HFS unix file, some more glue logic is required.
I have reordered the terms in the `if` statements to make it clearer that they primary criteria is `if (zos...)` and that the term `path.StartsWith("/")` is ancillary to that. In words: If it is **z/OS**, we need special handling, **unless** the path starts with a slash, then we can be **sure** to use standard unix methods.
> Clean up FileExists for z/OS - better no SIZE, no MDTM on non HFS files

- FluentFTP/Client/FtpClient_FileUpload.cs
This was omitted in the ASYNC part in #741
> Duplicate #741 for ASYNC

- FluentFTP/FluentFTP.csproj
> FIX: Remove superfluous reference to System.Net.Primitives in net45

- FluentFTP/FluentFTP.csproj
Reverts robinrodricks/FluentFTP#834
> Revert "FIX: Remove superfluous reference to System.Net.Primitives in net45"

- FluentFTP/Streams/FtpSocketStream.cs
This PR disposes the `CancellationTokenSource` added in #822.
It is also only necessary to create a single `CancellationTokenSource`.
> Dispose CancellationTokenSource

- FluentFTP/Client/FtpClient_FXPFileTransfer.cs
- FluentFTP/Client/FtpClient_FXPFolderTransfer.cs
- FluentFTP/Client/FtpClient_FolderDownload.cs
- FluentFTP/Client/FtpClient_FolderUpload.cs
- FluentFTP/Client/FtpClient_Properties.cs
- FluentFTP/Client/FtpClient_Stream.cs
- FluentFTP/Model/FtpProgress.cs
- FluentFTP/Model/FtpResult.cs
- FluentFTP/Rules/FtpFolderNameRegexRule.cs
- FluentFTP/Rules/FtpFolderNameRule.cs
- FluentFTP/Utils/NET2Compatibility.cs
- NOTES.md
- README.md
This fixes some typos in comments and documentation.
No functionality is changed.
> Fix some typos

- FluentFTP/Client/FtpClient_Stream.cs
Fixes error while downloading file through SOCKS4 / SOCKS4a proxy
> Fixes error with downloading while using SOCKS4/SOCKS4a proxy

- FluentFTP.Dockers/proftpd/Dockerfile
- FluentFTP.Dockers/proftpd/docker-entrypoint.sh
- FluentFTP.Xunit/Docker/Containers/ProFtpdContainer.cs
Related #903
This creates an image that will start without error,
and where the ftp server can be used without mounting a volume for users home directory.
> Make ProFtp Dockerfile work.

- FluentFTP/Client/FtpClient_Listing.cs
- FluentFTP/Servers/FtpBaseServer.cs
- FluentFTP/Servers/Handlers/IbmZosFtpServer.cs
I am trying to help remove (step by step) direct code dependencies on z/OS.
> Remove direct z/OS dependancy in GetListing

- FluentFTP/Helpers/RemotePaths.cs
Some special cases were missing when calculation item.Fullname
> RemotePaths: Add some special cases for item.Fullname

- FluentFTP.Tests/Unit/ParserTests.cs
- FluentFTP/Helpers/Parsers/IBMzOSParser.cs
Adding the still missing parser tests for all 4 realms of the z/OS FTP server
> Add missing parser tests for z/OS FTP server

- FluentFTP/Client/FtpClient_FileDownload.cs
- FluentFTP/Servers/FtpBaseServer.cs
- FluentFTP/Servers/Handlers/IbmZosFtpServer.cs
> Remove direct z/OS dependency ReadToEnd in Download

- FluentFTP/Streams/FtpSocketStream.cs
> Concerns issue 954: One more place to save/close the socket

- FluentFTP/Client/AsyncClient/DeleteDirectory.cs
- FluentFTP/Client/SyncClient/DeleteDirectory.cs
New function overload (Wiki API will need update) to allow users of `DeleteDirectory` to optionally make this function leave the top level directory intact.
Using this will prevent use of any highly optimised server side RMDIR functionality on the uppermost level, but that's the price.
Usage:
```
/// <summary>
/// Deletes the specified directory and all its contents.
/// </summary>
/// <param name="path">The full or relative path of the directory to delete</param>
/// <param name="options">Useful to delete hidden files or dot-files.</param>
/// <param name="deleteFinalDir">Delete the top level dir too</param>
public void DeleteDirectory(string path, FtpListOption options, bool deleteFinalDir = true)
```
The default for `deleteFinalDir` is `true`, which is the normal behaviour right now.
> DeleteDirectoryContents: New API to leave top level dir intact

- FluentFTP/Streams/FtpSocketStream.cs
See issue #823 
NOOPs work fine for non-SSL connections.
NOOPs work fine for SSL connections that are not buffered.
NOOP handling currently fails miserably when SSL connections are buffered.
Since a user who activates NOOPs (by setting `Config.NoopInterval` to some value `> 0`) very probably is very much in need of the "keep-alive" functionality of this feature, turn off buffering when creating the stream, even if `Config.SslBuffering` has been requested (`On` or `Auto`).
Since there are other reasons also, when SSL Buffering is disabled, I have added warning messages telling the user that this has happened. Previously, this was done silently, possibly causing confusion.
Example:
```
Response: 150 Opening BINARY mode data connection for /home/mike/test2 (1073741824 bytes)
Warning:  SSL …
```
> Fix823 noop

- FluentFTP/Client/BaseClient/ReadStaleData.cs
Once again a useful verbose message to easier understand what is happening in the log
> Better messaging for debugging

- FluentFTP/Helpers/Parsers/IBMzOSParser.cs
It was on the todo list to fix this
> Remove unused "var test" due to Codacity complaints

- FluentFTP/Client/Interfaces/IBaseFtpClient.cs
> LastReplies needs to be included in the interface

- FluentFTP.Dockers/Build.sh
Since the glftpd integration test server works, add this build command to the build.sh also.
> Add glftpd in build.sh too

- FluentFTP.Dockers/proftpd/run-proftpd.sh
- FluentFTP.Dockers/pureftpd/run-pureftpd.sh
- FluentFTP.Dockers/vsftpd/run-vsftpd.sh
Just make all first-party server be as equal as possible. Details, details, details...
> Small comment/Echo tweak

- FluentFTP/Client/AsyncClient/GetListing.cs
- FluentFTP/Client/SyncClient/GetListing.cs
> Eat 6 bytes if Proxy4a GetListing

- FluentFTP/Client/AsyncClient/Execute.cs
As usual, Async also needs the same change
> Async Execute Conditional PostExecute

- FluentFTP/Client/AsyncClient/SetWorkingDirectory.cs
- FluentFTP/Client/SyncClient/SetWorkingDirectory.cs
> Remove comment

- FluentFTP.Xunit/Docker/Containers/ApacheContainer.cs
- FluentFTP.Xunit/Docker/DockerFtpContainerIndex.cs
- FluentFTP/Enums/FtpServer.cs
and add Apache Docker Container
and make container list alphabetic
> Add Apache FTP Server Enum

- FluentFTP/Enums/FtpServer.cs
- FluentFTP/Servers/FtpHandlerIndex.cs
and delete whitespace in `FluentFTP/Servers/FtpHandlerIndex.cs`
> Alphabetize FtpServer Enum

- FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
- FluentFTP/Client/SyncClient/DownloadFileInternal.cs
For consistency: offset oper fileLen, then  || readToEnd on all if statements.
> Cosmetic change, make this if the same format as the two others.

- FluentFTP/Client/AsyncClient/MoveFile.cs
- FluentFTP/Client/SyncClient/MoveFile.cs
I suppose this is what was intended.
> Change to MoveFile issue 1054

- FluentFTP.Dockers/Build.bat
- FluentFTP.Dockers/Build.sh
- FluentFTP.Dockers/apache/Dockerfile
- FluentFTP.Dockers/bftpd/Dockerfile
- FluentFTP.Dockers/common-debian-slim/Dockerfile
- FluentFTP.Dockers/common-debian/Dockerfile
- FluentFTP.Dockers/common-mirror/Dockerfile
- FluentFTP.Dockers/common-mirror/run.sh
- FluentFTP.Dockers/filezilla/Dockerfile
- FluentFTP.Dockers/glftpd/Dockerfile
- FluentFTP.Dockers/proftpd/Dockerfile
- FluentFTP.Dockers/pureftpd/Dockerfile
- FluentFTP.Dockers/vsftpd/Dockerfile
Improve Docker Build by attempting to find better mirror and by using pre-built utility images.
> Improved Docker Build Process

- FluentFTP/Client/BaseClient/Properties.cs
Bring in the `ValidateCertificateHandlerExists` method.
> Prepare for ReConnect PR

- .editorconfig
Use the .editorconfig that @jnyrup proposed for FluentFTP in **master**
> Update .editorconfig to be FluentFTP conformant

- .editorconfig
Something else went wrong when formatting some of the code. My bad.
> Bring back previous .editorconfig, it was ok after all. 

- FluentFTP/Client/SyncClient/DownloadFileInternal.cs
Very strange, but VS2022 is falsely formatting the second commit on each pull request, I don't understand why. .editorconfig was my first suspicion, but it seems I need to stop and restart VS2022 after each single commit.
> Fix formatting

- FluentFTP/Client/Interfaces/IFtpClient.cs
Same ordering for Sync and Async
> Cosmetic: Reorder

- FluentFTP.Tests/Unit/ParserTests.cs
Lots of warnings re. nullable vs. non-nullable.
> Clear up all warnings re. ParserTests.c

- FluentFTP.Tests/Unit/ParserTests.cs
Using the "null forgiving operator" "!"
> Improve previous change to ParserTests.cs

- FluentFTP/Client/AsyncClient/UploadFileInternal.cs
- FluentFTP/Client/SyncClient/UploadFileInternal.cs
Analogous to the logic in download for unsized stream
> Fix unsized stream Timeout detection

- FluentFTP/Client/BaseClient/GetPassivePort.cs
> Handle | vs. ! on EBCDIC code page fault

- FluentFTP.Dockers/Build.bat
- FluentFTP.Dockers/Build.sh
Allow the user to save some disk space if he needs it.
> Small tweak to build process

- FluentFTP/Client/BaseClient/Logger.cs
Fixup from my prototype written yesterday just before I went to bed.
> send full message to logger

- FluentFTP/Client/AsyncClient/Connect.cs
- FluentFTP/Client/AsyncClient/GetListing.cs
- FluentFTP/Client/AsyncClient/OpenActiveDataStream.cs
- FluentFTP/Client/AsyncClient/OpenPassiveDataStream.cs
- FluentFTP/Client/AsyncClient/SetWorkingDirectory.cs
- FluentFTP/Client/AsyncClient/UploadFileInternal.cs
- FluentFTP/Client/BaseClient/CalculateAppendLocalPosition.cs
- FluentFTP/Client/BaseClient/VerifyTransferFileParams.cs
- FluentFTP/Client/Modules/ConnectModule.cs
- FluentFTP/Client/SyncClient/Connect.cs
- FluentFTP/Client/SyncClient/GetListing.cs
- FluentFTP/Client/SyncClient/OpenActiveDataStream.cs
- FluentFTP/Client/SyncClient/OpenPassiveDataStream.cs
- FluentFTP/Client/SyncClient/SetWorkingDirectory.cs
- FluentFTP/Client/SyncClient/UploadFileInternal.cs
- FluentFTP/Helpers/Enums.cs
- FluentFTP/Helpers/FtpListParser.cs
- FluentFTP/Helpers/RemotePaths.cs
- FluentFTP/Streams/FtpSocketStream.cs
Simplify conditionals with [logical patterns](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#logical-patterns)
> use logical patterns

- FluentFTP/Streams/FtpSocketStream.cs
> Log exception

- FluentFTP/Client/BaseClient/StartListeningOnPort.cs
- FluentFTP/Streams/FtpSocketStream.cs
Spotted some places where exception handling could be simplified with `when`.
> Simplify catch with 'when'

- FluentFTP/Client/BaseClient/Logger.cs
- FluentFTP/Client/Interfaces/IInternalFtpClient.cs
- FluentFTP/Streams/FtpSocketStream.cs
This was suggested at the end of the discussion in #1123
> Write exception (optionally) on a new line

- FluentFTP/Streams/FtpSocketStream.cs
`#if v472` is never true and caused `ConnectAsync` not to be used on net472.
See how VS highlights that with net472 selected, the else part is used.
The correct preprocessor directive would be `#if NET472`.
I also took the liberty to rearrange this a bit as most of the code is identical, except net462 should use `BeginConnect` and non-netstandard should also catch `ObjectDisposedException`.
The GitHub diff might not be the easiest way to look at this.
Fixup to #1056
> Use `ConnectAsync` for net472

- FluentFTP/Client/AsyncClient/Connect.cs
> Remove setting CurrentDataType to unknown

- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/BaseClient/Execute.cs
One more thing needed to be done:
If a CWD command is intercepted, we did set the CurrentWorkingDirectory status variable to "null".
This is correct operation. We don't really know where the CWD command has taken us. It might have been a relative move, and absolute move or whatever.
But: If a subsequent reconnect happens at any time before we ever see a directory path, this value will still be null. Thus, after a CWD we need to "find out" where we are.
Why? Because there are some reconnect cases where we no longer have a control connection and thus cannot do a PWD before we reconnect.
We need to know where we are so that after a reconnect, we can go to that location prior to continuing operations.
> Refactor "Execute" and improve logging

- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/BaseClient/Execute.cs
- FluentFTP/Streams/FtpSocketStream.cs
Refactor: Rename SocketReadLineCount to SessionLength
> Need debug info on current SessionLength, rename SocketReadLineCount to SessionLength

- FluentFTP/Client/BaseClient/GetReply.cs
Looks like so:
```
Status:   Waiting for a response
Response: 226 Transfer complete [0,048s]
```
> Add command duration to log message

- FluentFTP/Client/BaseClient/GetReply.cs
- FluentFTP/Helpers/TimeSpans.cs
- FluentFTP/Streams/FtpSocketStream.cs
> Duration also for authentication message

- FluentFTP/Client/AsyncClient/GetReply.cs
- FluentFTP/Client/BaseClient/GetReply.cs
Help for #1156 Infinite loop potential
> Move connectivity test into the loop

- FluentFTP/Client/AsyncClient/Noop.cs
- FluentFTP/Client/SyncClient/Noop.cs
Add comment in NOOP to document possible future enhancement of NOOP commands
> Comment re possible NOOP enhancement

- FluentFTP/Client/SyncClient/OpenActiveDataStream.cs
- FluentFTP/Streams/FtpSocketStream.cs
See issue #648 - needs some attention and see the comment itself
> Important comment

- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/BaseClient/Execute.cs
SslSessionLength information is only interesting on encrypted connections
> Improve message wording Part 3

- FluentFTP/Client/AsyncClient/OpenActiveDataStream.cs
- FluentFTP/Client/SyncClient/OpenActiveDataStream.cs
- FluentFTP/Streams/FtpSocketStream.cs
Best to read the trailing end of issue #648  - this small change should be harmless and really helps the Mono users. This should not be construed as an pledge to support Mono - this is not the case.
> Small change to help Mono users (see #648)

- FluentFTP/Client/AsyncClient/GetObjectInfo.cs
in my test case ,it works for me
> #some times the `InfoMessages` maybe null

- FluentFTP.Tests/Unit/ParserTests.cs
- FluentFTP/Helpers/Parsers/WindowsParser.cs
Makes the parse a little more "generic" DOS/WINDOWS/IIS. See #1240
> Fix 1st part of #1240 - position independant parse

- FluentFTP/Client/Modules/ConnectModule.cs
> Change spelling re #1247

- FluentFTP/Client/Modules/ConnectModule.cs
To address the noted "dead code" and general cleanup of `Is PermanentConnectionFailure.cs`:
Essentially only a reordering of the code if-segments.
> Re-ordering of code re. #1247

- FluentFTP/Streams/FtpSocketStream.cs
Sequential logic for better understanding of what happens when where and why.
This came up whilst investigating #1251.
> Better bufferstream create logic

- FluentFTP/Client/AsyncClient/OpenDataStream.cs
- FluentFTP/Client/BaseClient/GetPassivePort.cs
- FluentFTP/Client/Modules/ConnectModule.cs
- FluentFTP/Client/SyncClient/OpenDataStream.cs
- FluentFTP/Enums/FtpDataConnectionType.cs
See issues #1258, #409, #270
Sequential logic pattern makes this easer to maintain.
> New connection type PASVUSE, better GetPassivePort.cs

- FluentFTP/Client/Modules/ConnectModule.cs
Some more changes:
Add some logging to see the order of combinations Auto-Detect will test.
There are not many combinations though:
With .NET Framework 4.6.2+ (and 4.7.2+) and .NET Standard 2.0+, you can set protocols to:
`None`, which is recommended but might connect to TLS13, which is fraught with errors. So NOGO
`Default`, which is **not to be used**. See Microsoft on this. It would want to connect SSL or TLS10, which is obsolete
`TLS11|TLS12` is the only real sensible choice left over.
So the only tests left over are "AUTO/TLS11|TLS12" and "NONE/.........".
> Final tweaks to Auto-Detect, better logging

- FluentFTP/Client/Modules/ConnectModule.cs
This is just to make the AutoDetect logging message better looking:
`Status:   Auto-Detect trying encryption mode "Auto" with "Tls11, Tls12"`
> Further improve AutoDetect logging

- FluentFTP/Client/Modules/ServerStringModule.cs
> Add RNFM/RNTO to critical sequence commands list.

- FluentFTP/Client/AsyncClient/AutoDetect.cs
- FluentFTP/Client/Interfaces/IAsyncFtpClient.cs
- FluentFTP/Client/Interfaces/IFtpClient.cs
- FluentFTP/Client/SyncClient/AutoDetect.cs
> AutoDetect: Allow and handle legacy format calls

- FluentFTP/Client/AsyncClient/AutoDetect.cs
- FluentFTP/Client/Modules/ConnectModule.cs
- FluentFTP/Client/SyncClient/AutoDetect.cs
- FluentFTP/Helpers/ValuePrinter.cs
AutoDetect new logic still had some small oversights
> closes #1316

- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/AsyncClient/GetListing.cs
- FluentFTP/Client/SyncClient/GetListing.cs
- FluentFTP/Enums/FtpListingWrapType.cs
- FluentFTP/Model/FtpConfig.cs
and make the wrapping optional as a global config option.
> Add optional CWD wrapping for GetListing commands

- FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
- FluentFTP/Client/AsyncClient/GetListing.cs
- FluentFTP/Client/AsyncClient/UploadFileInternal.cs
- FluentFTP/Client/SyncClient/DownloadFileInternal.cs
- FluentFTP/Client/SyncClient/GetListing.cs
- FluentFTP/Client/SyncClient/UploadFileInternal.cs
- FluentFTP/Enums/FtpNavigate.cs
- FluentFTP/Model/FtpConfig.cs
This handles GetListing, anything that calls UploadFileInternal, anything that calls DownloadFileInternal.
> Navigation Manual, Auto, SemiAuto + optional Conditional

- FluentFTP/Client/AsyncClient/UploadFileInternal.cs
- FluentFTP/Client/SyncClient/UploadFileInternal.cs
> Fiy remoteDir <- typo

- FluentFTP/Client/BaseClient/ReadStaleData.cs
Happens when a socket is closed by the far side and socket still has unread data, which then can't be read successfully.
> Prevent loop on stale data read when socket stalled

- FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
- FluentFTP/Client/AsyncClient/OpenAppend.cs
- FluentFTP/Client/AsyncClient/OpenRead.cs
- FluentFTP/Client/AsyncClient/OpenWrite.cs
- FluentFTP/Client/SyncClient/DownloadFileInternal.cs
- FluentFTP/Client/SyncClient/OpenAppend.cs
- FluentFTP/Client/SyncClient/OpenRead.cs
- FluentFTP/Client/SyncClient/OpenWrite.cs
…in order to help in debugging and reorder signature
> Update function call logging for OpenAppend, OpenRead and OpenWrite 

- FluentFTP/Proxy/Socks/SocksProxy.cs
This now matches the sync negotiation
> Correctly set supported method in socks5 negotiation

- FluentFTP/Client/AsyncClient/GetListing.cs
- FluentFTP/Client/BaseClient/Logger.cs
- FluentFTP/Client/Interfaces/IAsyncFtpClient.cs
- FluentFTP/Streams/FtpSocketStream.cs
> Clean up NET50_OR_LATER -> NET5_0_OR_GREATER

- FluentFTP/Client/BaseFtpClient.cs
Uri.SchemeFtp is available in all our targets
> Remove conditional compile as unneeded

- FluentFTP/FluentFTP.csproj
Time to document the current state of affairs in .csproj re TFMs.
> Documentation PR for FluentFTP.csproj

- FluentFTP/Client/BaseClient/ReadStaleData.cs
This will help a lot for cases where we lose the control connection.
> Fix missing ASYNC mods in staledata.cs, add some diagnostics and enhance behaviour in staledata.cs

- FluentFTP/Client/BaseClient/Daemon.cs
- FluentFTP/Streams/FtpSocketStream.cs
> Beautify daemon, optimize termination of daemon

- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/BaseClient/Execute.cs
Remove some duplicated code and add an additional m_sema wait for synchronisation
> Improve Execute.cs code for semaphore and NoopTestConnectivity

- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/AsyncClient/IsStillConnected.cs
- FluentFTP/Client/AsyncClient/Noop.cs
- FluentFTP/Client/AsyncFtpClient.cs
- FluentFTP/Client/BaseClient/Daemon.cs
- FluentFTP/Client/BaseClient/Execute.cs
- FluentFTP/Client/BaseClient/GetReply.cs
- FluentFTP/Client/BaseClient/IsStillConnected.cs
- FluentFTP/Client/BaseClient/Noop.cs
- FluentFTP/Client/FtpClient.cs
- FluentFTP/Client/SyncClient/IsStillConnected.cs
Remove last unneeded interface artifact
Cleanup Sync/Async IsStillConnected
Improve log text
Improve Daemon logic
No need for a NOOP before QUIT command
Improve logging GetReply NOOP/stale
> Final adjustments to NOOP logic

- FluentFTP/Client/BaseClient/GetReply.cs
instead of InvariantCultureIgnoreCase
> Recognize NOOPs in OrdinalIgnoreCase

- FluentFTP/Servers/Handlers/IBMOS400FtpServer.cs
> Enhance detection of OS/400 and setup LISTFMT and NAMEFMT to 1 on connect

- FluentFTP/Client/AsyncClient/Connect.cs
Discovered while investigating the disconnect/dispose logic re. #1460/#1461
> Connect.cs: This needs an await

- FluentFTP/Client/BaseClient/Logger.cs
- FluentFTP/Client/BaseClient/Properties.cs
- FluentFTP/Client/BaseFtpClient.cs
> Indicate creating / disposing SYNC or ASYNC in log

- FluentFTP/Client/AsyncFtpClient.cs
- FluentFTP/Client/BaseClient/CloseDataStream.cs
- FluentFTP/Client/BaseClient/Dispose.cs
- FluentFTP/Client/BaseFtpClient.cs
- FluentFTP/Client/Interfaces/IAsyncFtpClient.cs
- FluentFTP/Client/Interfaces/IInternalFtpClient.cs
Before even considering any improvements to *async "stream" disposal*, here are the things that were needed to make **async "client" disposal** improvements complete.
> Final touches for Async Client Dispose feature

- FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
- FluentFTP/Client/AsyncClient/UploadFileInternal.cs
- FluentFTP/Client/SyncClient/DownloadFileInternal.cs
- FluentFTP/Client/SyncClient/UploadFileInternal.cs
Prevents control conversation going totally out of sync
> Pick up any replies if Up/Download aborts

- FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
- FluentFTP/Client/AsyncClient/UploadFileInternal.cs
- FluentFTP/Client/BaseClient/Daemon.cs
- FluentFTP/Client/SyncClient/DownloadFileInternal.cs
- FluentFTP/Client/SyncClient/UploadFileInternal.cs
- FluentFTP/Streams/FtpSocketStream.cs
So this will be V50.0.1, then.
> Fix V50.0.0 regressions

- FluentFTP/Streams/FtpSocketStream.cs
`Connecting(sync) FtpClient.FtpSocketStream(data) IP #1= ***:43433`
and
`Disposing(sync) FtpClient.FtpSocketStream(data)`
> Log message text improvements

- FluentFTP/Client/Modules/LogMaskModule.cs
Change the message
`227 Entering Passive Mode (192,168,1,243,162,237).`
to 
`227 Entering Passive Mode (***,***,***,***,162,237).`
when `Config.LogHost` is false.
> Hide IPAD in PASV command response

- FluentFTP.Tests/Unit/CustomTests.cs
Adding some comments
Making the tests "succeed" if they have not been customized by the user at all
> Improve "Custom Tests"

- FluentFTP/Client/AsyncClient/GetNameListing.cs
- FluentFTP/Client/SyncClient/GetNameListing.cs
> Make log message consistent with format used elsewhere. 

- FluentFTP/Streams/FtpSocketStream.cs
Nice to know **for sure** if connectivity test is for control or data connection
> Improve log message for better debug

- FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
- FluentFTP/Client/AsyncClient/UploadFileInternal.cs
- FluentFTP/Client/SyncClient/DownloadFileInternal.cs
- FluentFTP/Client/SyncClient/UploadFileInternal.cs
Avoid DivideByZeroException more elegantly
> Improve Up/Download speed calculation

- FluentFTP/Client/BaseClient/NoopDaemon.cs
Make it more readable and add some small safety changes
> Refactor NOOP Daemon

- FluentFTP/Client/AsyncClient/DownloadFileInternal.cs
- FluentFTP/Client/AsyncClient/UploadFileInternal.cs
- FluentFTP/Client/BaseClient/NoopDaemon.cs
- FluentFTP/Client/SyncClient/DownloadFileInternal.cs
- FluentFTP/Client/SyncClient/UploadFileInternal.cs
- FluentFTP/Model/FtpClientState.cs
Like
`Status:   Uploaded 1 bytes (<1ms, ?/s), 0 NOOPs`
> Improve Up/Download success message format

- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/AsyncClient/Noop.cs
- FluentFTP/Client/BaseClient/Execute.cs
- FluentFTP/Client/BaseClient/GetReply.cs
- FluentFTP/Client/BaseClient/Noop.cs
- FluentFTP/Client/BaseClient/NoopDaemon.cs
- FluentFTP/Client/BaseClient/Properties.cs
- FluentFTP/Proxy/SyncProxy/FtpClientHttp11Proxy.cs
Well, @robinrodricks, you will still get your chance to improve the names :-) As you can see, I am floundering...
> Final name for the daemon blocking Semaphore

- FluentFTP/Client/SyncClient/Disconnect.cs
> Yet one more Git glitch

- FluentFTP/Streams/FtpSocketStream.cs
Speed transfers up - most visible on the data channel with large frames
> Use AsMemory for Read and Write from/to buffer

- FluentFTP/Streams/FtpSocketStream.cs
> Follow up to #1613

- FluentFTP/Streams/FtpSocketStream.cs
This reverts commit 3769970ff6a60fcf6b4044eb8b5a03c06476037f.
Integration tests fail
> Revert "Follow up to #1613"

- FluentFTP/Streams/FtpDataStream.cs
- FluentFTP/Streams/FtpSocketStream.cs
- FluentFTP/Streams/FtpSslStream.cs
Some small changes for the dispose/close logic to avoid deadlocks on same thread scenarios (like GUI)
> Improve Async & GUI cohabitation

- FluentFTP.Tests/Unit/ConstructorTests.cs
- FluentFTP/Client/AsyncFtpClient.cs
- FluentFTP/Client/FtpClient.cs
- FluentFTP/Client/Modules/LogMaskModule.cs
This is my recommended fix. However, I wasn't able to build this due to many `IDE0032` errors, and I didn't want to touch anywhere in the codebase. Should build fine though.
> fix LogMaskModule throwing exception when UserName is empty (fixes #1649)

- FluentFTP.Tests/Unit/HelperTests.cs
- FluentFTP.VBExamples/ExecuteFTPCommand.vb
- FluentFTP/Client/AsyncClient/DownloadUriBytes.cs
- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/AsyncClient/ExecuteDownloadText.cs
- FluentFTP/Client/AsyncClient/GetListing.cs
- FluentFTP/Client/AsyncClient/GetNameListing.cs
- FluentFTP/Client/AsyncClient/Noop.cs
- FluentFTP/Client/SyncClient/ExecuteDownloadText.cs
- FluentFTP/Client/SyncClient/GetListing.cs
- FluentFTP/Client/SyncClient/GetNameListing.cs
- FluentFTP/Helpers/Parsers/WindowsParser.cs
Some small changes to remove WARNINGs on build and also add token forwarding in async methods where it was missing
> Fix all build WARNING messages

- .editorconfig
- FluentFTP.Tests/Integration/System/IntegrationTestSuite.cs
- FluentFTP.Xunit/Attributes/Internal/SkippableFactTestCase.cs
- FluentFTP.Xunit/Docker/DockerFtpContainer.cs
- FluentFTP/Client/AsyncClient/DiscoverSslSessionLength.cs
- FluentFTP/Client/AsyncClient/IsStillConnected.cs
- FluentFTP/Client/BaseClient/CloseDataStream.cs
- FluentFTP/Client/BaseClient/IsStillConnected.cs
- FluentFTP/Client/BaseClient/Noop.cs
- FluentFTP/Client/SyncClient/GetChecksum.cs
- FluentFTP/Exceptions/FtpMissingObjectException.cs
- FluentFTP/Streams/FtpSocketStream.cs
Lots of trivial stuff, but cleaner this way.
> Fix more WARNINGs on build

- README.md
Commit e2633a5bd4f0a4f43ebdd971d89eaac9ad1898ff moved the location of `FtpClientProxy.cs`. This PR adjusts sources to changes.
> Update FtpClientProxy reference

- FluentFTP/Client/BaseClient/Dispose.cs
- FluentFTP/Client/BaseFtpClient.cs
- FluentFTP/Client/Interfaces/IAsyncFtpClient.cs
> Modify interface AsyncDispose logic

- FluentFTP/Client/AsyncClient/DownloadFiles.cs
- FluentFTP/Client/AsyncClient/UploadFiles.cs
- FluentFTP/Client/SyncClient/DownloadFiles.cs
- FluentFTP/Client/SyncClient/UploadFiles.cs
- FluentFTP/Helpers/Enums.cs
> Improve DownloadFiles/UploadFiles result setting

- FluentFTP/Client/BaseClient/ReadStaleData.cs
Step 1 to address this reported problem
> See #1676 - Loosen tight CPU loop

- FluentFTP/Client/AsyncClient/OpenDataStream.cs
- FluentFTP/Client/SyncClient/OpenDataStream.cs
See #1662 
This code probably never really worked.
> This reconnect totally incomplete and also unneeded

- FluentFTP/Client/BaseClient/Properties.cs
- FluentFTP/Client/Interfaces/IBaseFtpClient.cs
- FluentFTP/Streams/FtpSocketStream.cs
```cs
client.Connect();
Console.WriteLine("Selected SSL Version/Protocol " + client.SslProtocolActive);
Console.WriteLine("Selected SSL Ciphersuite " + client.SslCipherSuiteActive);
```
Result:
```
Selected SSL Version/Protocol Tls12
Selected SSL Ciphersuite Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 255)
```
> Reveal CipherSuite in addition to SslProtocol

- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/BaseClient/Execute.cs
- FluentFTP/Client/BaseClient/Features.cs
- FluentFTP/Client/BaseClient/Properties.cs
- FluentFTP/Enums/FtpNavigate.cs
- FluentFTP/Enums/FtpSelfConnectMode.cs
- FluentFTP/Model/FtpConfig.cs
See #1704 for the information on this PR
This is a cleaned up final version of #1704, rebased to show all changes and it can be merged.
> New config option: FtpSelfConnectMode

- FluentFTP/Client/AsyncClient/OpenActiveDataStream.cs
- FluentFTP/Client/SyncClient/OpenActiveDataStream.cs
> Set connection state after connect in Active mode

- FluentFTP/Client/Modules/ServerStringModule.cs
This german text is not being used at all. No reference to it.
> Remove language specific checks - PART 2

- FluentFTP/Client/AsyncClient/IsStillConnected.cs
- FluentFTP/Client/BaseClient/IsStillConnected.cs
> Issue #1744: NOOP command failure does not indicate disconnection

- FluentFTP/Client/AsyncClient/DirectoryExists.cs
- FluentFTP/Client/AsyncClient/Execute.cs
- FluentFTP/Client/AsyncClient/SetWorkingDirectory.cs
- FluentFTP/Client/BaseClient/Execute.cs
- FluentFTP/Client/SyncClient/DirectoryExists.cs
- FluentFTP/Client/SyncClient/SetWorkingDirectory.cs
- FluentFTP/Model/FtpConfig.cs
See issue / Enhancement request #1757
Adds config parm `Config.PreserveTrailingSlashCmdList`
> Preserve trailing slashes for special servers

- FluentFTP/Client/BaseClient/GetReply.cs
Remove debug code and reorder exception handling
> Tweaks for better debugging
